### ISSUE TITLE
Post pagination

### ISSUE THREAD

**Issue by Fisiu** [jbake-org/jbake#101]
It would be nice to have post pagination on index page. Let's allow user to configure how many posts should be visible on index page.

Use case:
If post count > specified limit, then allow to switch to ie. index2. On index2 user can switch back to index or go to index3 when there is more posts.

On the frontend side, it could be done with http://getbootstrap.com/components/#pagination-pager.

**Comment by jonbullock** [comment]
Implemented as part of #186
