### ISSUE TITLE
Consider moving to Java 7

### ISSUE THREAD

**Issue by mwanji** [jbake-org/jbake#107]
The main benefit, I think, would be the native file system watching ability. That would allow automatic re-baking when a change occurs (for example with a -w flag) and would tie in very nicely with the incremental build system.

A minor benefit would be the new language features and APIs. They seem minor, but I end up using try-with-resources and the various new utility classes a lot more than I thought I would.

I don't think this would impact people using JBake as an app, as Java 7 has been the default install for years. It might have a greater impact on those using it as a library. Is anyone embedding it in Java 6 apps?

**Comment by wenerme** [comment]
About year ago, still 2.x. :disappointed:

**Comment by jonbullock** [comment]
Don't worry we'll get onto v3.0.0 soon enough :smile:

**Comment by msgilligan** [comment]
Why not move to Java 8? By it's nature JBake is a standalone tool installed on an individual machine that generates static output that is pushed to the server. So there's no worry about any runtime requirements other than in the build tools themselves. Java 7 is reaching end-of-maintenance (or whatever) and Java 8  offers significant improvements.

I'd love to see v3.0.0 support Java 8.

**Comment by msgilligan** [comment]
I created issue #224 asking for Java 8. If there is agreement that we should skip Java 7 than this issue can be closed in favor of that issue.

**Comment by jonbullock** [comment]
I've not got any issue in jumping straight to Java 8 and skipping Java 7.

If anyone has any issues with this please plan voice them here.

**Comment by jangalinski** [comment]
since Java 7 is out of support already: +1 for closing this one and skip to java 8.

**Comment by jonbullock** [comment]
Done as part of #280

**Comment by msgilligan** [comment]
Nice work! Gradle, too! Awesome!
