### ISSUE TITLE
Pager / Paginator 

### ISSUE THREAD

**Issue by huima** [jbake-org/jbake#115]
Hi,

one thing that is missing from very necessary features is some kind of paginator.

I tried to look from documentation as well as from the sourcecode and did not notice how it could be possible to limit the number of posts on the index page and/or paginate the index page to multiple pages.

For example Jekyll does this quite nicely, as well as Nikola.

Any thoughts yet on when and where to implement this kind of functionality.

**Comment by jonbullock** [comment]
Implemented as part of #186
