### ISSUE TITLE
Customizable index page

### ISSUE THREAD

**Issue by Vad1mo** [jbake-org/jbake#145]
My index.ftl page contains different content then a list of pages or posts like in the examples. I would like to have a ./content/index.adoc file
that is rendered to /index.html any idea how that can be achieved?

```
= My Homepage
:jbake-type: index
:jbake-status: published

== My index page content
...
```

**Comment by haumacher** [comment]
Just to de-mystify "In your jbake.properties you can configure the special index file not to be rendered...":

One has to set
```
render.index=false
```
in the `jbake.properties` of the site.

**Comment by jonbullock** [comment]
Yes that's correct, the docs now cover this option: http://jbake.org/docs/2.4.0/#render_index_file
