### ISSUE TITLE
Improve use as library: Remove System.exit() calls

### ISSUE THREAD

**Issue by lefou** [jbake-org/jbake#167]
To use JBake as a library (e.g. as a plug-in in a build tool) without unforseen surprises, calls to `System.exit()` should be removed. I suggest to replace them with a dedicated `JBakeException`s. The exit calls cannot be easily inhibited and stopping the whole JVM from a library is a no go IMHO. Whereas dedicated exception can be handled very easily.

Please also see #120 which is primary about the commandline parser but also includes these removals of `System.exit()`.

**Comment by vietj** [comment]
+1

**Comment by stavytskyi** [comment]
+1
