### ISSUE TITLE
Since 2.3.0 tags rendering is broken.

### ISSUE THREAD

**Issue by Fisiu** [jbake-org/jbake#170]
I'm using some jbake for some time. The last version which was working fine was 2.2.1. Everything newer then 2.2.1 fails during tags rendering with something like:
```
JBake v2.3.0 (2014-05-11 15:50:07PM) [http://jbake.org]
(...)
23:41:42.853 ERROR org.jbake.app.Oven - Failed to bake 1 item(s)!
JBake failed with 1 errors:
1. Unable to convert object to String[]
```

```
JBake v2.3.1 (2014-07-10 20:08:10PM) [http://jbake.org]
(...)
23:39:01.399 INFO  org.jbake.app.Oven - Baking finished!
23:39:01.399 INFO  org.jbake.app.Oven - Baked 33 items in 2174ms
23:39:01.399 ERROR org.jbake.app.Oven - Failed to bake 1 item(s)!
JBake failed with 1 errors:
1. Unable to convert object to String[]
```

```
JBake v2.3.2 (2014-09-21 01:47:44AM) [http://jbake.org]
(...)
23:47:43.845 INFO  org.jbake.app.Oven - Baking finished!
23:47:43.846 INFO  org.jbake.app.Oven - Baked 33 items in 2326ms
23:47:43.846 ERROR org.jbake.app.Oven - Failed to bake 1 item(s)!
sty 28, 2015 11:47:43 PM com.orientechnologies.common.log.OLogManager log
INFO: Shutting down storage: cache...
sty 28, 2015 11:47:43 PM com.orientechnologies.common.log.OLogManager log
INFO: Orient Engine shutdown complete

JBake failed with 1 errors:
1. Unable to convert object to String[]
```

And one more thing. If I set `render.tags=false`, `content.tags` (used in ie. templates/post.ftl) should be `null`? If so, then it's not a `null`.

**Comment by lefou** [comment]
Could you please attach the input file(s) which result in the error?

**Comment by Fisiu** [comment]
I use markdown for sources, so my post contains classic header:

    date=2014-03-27 15:12:27+01:00
    status=published
    title=Biblioteka Apache Tomcat Native w Eclipse
    type=post
    tags=openSUSE, java, eclipse, tomcat
    ~~~~~~
    [Content goes here]

My template for tags (tags.ftl) looks like:

```xml
<#include "header.ftl">
<#include "menu.ftl">

	    <div class="row">
        <#if config.sidebar_enabled?? && config.sidebar_enabled == "true">
          <div class="col-md-9">
        <#else>
          <div class="col-md-12">
        </#if>

            <article>
			  <h2>Tag #${tag?trim?replace(" ", "-")}</h2>
			  <hr>
              <#list tag_posts?sort_by("date")?reverse as post>
			    <#if (last_month)??>
				  <#if post.date?string("MMMM yyyy") != last_month>
              </ul>
			  <h4 class="well well-sm tag-month">${post.date?string("MMMM yyyy")}</h4>
              <ul>
				  </#if>
				<#else>
              <h4 class="well well-sm tag-month">${post.date?string("MMMM yyyy")}</h4>
              <ul>
                </#if>
			    <#assign last_month = post.date?string("MMMM yyyy")>
                <li>
                  <p>${post.date?string("dd")} - <a href="${post.uri}">${post.title}</a></p>
                </li>
			  </#list>
              </ul>
		    </article>

	      </div> <!-- /.col-md -->
          <#if config.sidebar_enabled?? && config.sidebar_enabled == "true">
            <#include "sidebar.ftl">
          </#if>
        </div> <!-- /.row -->


<#include "footer.ftl">
```

**Comment by lefou** [comment]
Thank you! Now, @jonbullock should have enough information to investigate.

**Comment by jonbullock** [comment]
This maybe related to: #128 & #129

The error is because of line: https://github.com/jbake-org/jbake/blob/1aa9b0319db04161817d06c380c2af92059e8f49/src/main/java/org/jbake/app/DBUtil.java#L60

Which file is not being rendered, is it a tag page or something else?

**Comment by Fisiu** [comment]
Tag files are not being rendered. I'll try to debug it.

2015-01-29 14:06 GMT+01:00 Jonathan Bullock <notifications@github.com>:

> This maybe related to: #128
> <https://github.com/jbake-org/jbake/issues/128> & #129
> <https://github.com/jbake-org/jbake/pull/129>
>
> The error is because of line:
> https://github.com/jbake-org/jbake/blob/1aa9b0319db04161817d06c380c2af92059e8f49/src/main/java/org/jbake/app/DBUtil.java#L60
>
> Which file is not being rendered, is it a tag page or something else?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jbake-org/jbake/issues/170#issuecomment-72020563>.
>



-- 
Pozdrawiam / Best regards,
Mariusz Fik,
openSUSE Community Member

**Comment by jonbullock** [comment]
Could you point me at the site/project source that's triggers this issue?

**Comment by Fisiu** [comment]
I tested current snapshot, and results are promising ;-)
With JBake v2.3.3-SNAPSHOT (2015-02-03 20:11:49PM) tags are being rendered
properly, but... When I open 'some tag' page, and then I can see posts url
as ${HOSTNAME}/tags/${post.uri} but they should not contain /tags/.

2015-01-31 10:31 GMT+01:00 Jonathan Bullock <notifications@github.com>:

> Could you point me at the site/project source that's triggers this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jbake-org/jbake/issues/170#issuecomment-72311039>.
>



-- 
Pozdrawiam / Best regards,
Mariusz Fik,
openSUSE Community Member

**Comment by Fisiu** [comment]
Ok, i resolved url issue with prepending “/“ before ${post.uri} in my
tags.ftl.

--- a/src/main/jbake/templates/tags.ftl+++
b/src/main/jbake/templates/tags.ftl@@ -24,7 +24,7 @@
                 </#if>
                            <#assign last_month = post.date?string("MMMM yyyy")>
                 <li>-                  <p>${post.date?string("dd")} -
<a href="${post.uri}">${post.title}</a></p>+
<p>${post.date?string("dd")} - <a
href="/${post.uri}">${post.title}</a></p>
                 </li>
                          </#list>
               </ul>

​

2015-02-03 20:27 GMT+01:00 Mariusz Fik <fisiu@opensuse.org>:

> I tested current snapshot, and results are promising ;-)
> With JBake v2.3.3-SNAPSHOT (2015-02-03 20:11:49PM) tags are being rendered
> properly, but... When I open 'some tag' page, and then I can see posts url
> as ${HOSTNAME}/tags/${post.uri} but they should not contain /tags/.
>
> 2015-01-31 10:31 GMT+01:00 Jonathan Bullock <notifications@github.com>:
>
>> Could you point me at the site/project source that's triggers this issue?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jbake-org/jbake/issues/170#issuecomment-72311039>.
>>
>
>
>
> --
> Pozdrawiam / Best regards,
> Mariusz Fik,
> openSUSE Community Member
>



-- 
Pozdrawiam / Best regards,
Mariusz Fik,
openSUSE Community Member

**Comment by jonbullock** [comment]
That'll be due to support for generating non-root sites, I'll double check the sample templates to make sure they are updated.

Thinking about it you could also put:
```
<a href="${content.rootpath}${post.uri}">${post.title}</a>
```

**Comment by Fisiu** [comment]
`${content.rootpath}` would solve post's url issue too. Anyway, we need to update documentation to include new [data models](http://jbake.org/docs/2.3.2/#data_model).
