### ISSUE TITLE
Special character in the title field of the meta-data header are not escaped

### ISSUE THREAD

**Issue by gilbertoca** [jbake-org/jbake#173]
The following example is causing issues:

title=Oracle JInitiator + Forms + IE6/IE7 + Windows Live Toolbar = Problema

Escaping it with \ didn't help:

title=Oracle JInitiator \+ Forms \+ IE6\/IE7 \+ Windows Live Toolbar \= Problema

**Comment by jonbullock** [comment]
Thanks Gilberto.

Code at https://github.com/jbake-org/jbake/blob/4a9732be7d3dc69367c1d7b0f5ce5d1a7b483066/src/main/java/org/jbake/app/Parser.java#L175 needs to allow usage of ```=``` in title
