### ISSUE TITLE
Add jbake -version OPTION

### ISSUE THREAD

**Issue by gilbertoca** [jbake-org/jbake#177]
-version print product version and exits the program

**Comment by jonbullock** [comment]
Thanks for the suggestion.

**Comment by mismatch** [comment]
Could you please clarify why do you need this option? Version is printed anytime you use JBake. You can run it without parameters to see version and exit program immediately.

**Comment by jonbullock** [comment]
I'm going to close this one as the behaviour has changed in 2.5.0 so running JBake with no options now shows the help by default which includes the version of the product.
