### ISSUE TITLE
org.jbake.template.RenderingException: java.lang.NullPointerException: Cannot invoke method contains() on null object

### ISSUE THREAD

**Issue by gilbertoca** [jbake-org/jbake#178]
I've build JBake locally (jbake-2.3.3-SNAPSHOT). Created a branch [1] with jbake -i groovy, copy my posts to that folder content, enabled tags in jbake.properties. Running jbake I got this exception in all posts - everyone has tags.

[1] https://github.com/gilbertoca/gilbertoca.com/tree/ybonnel-template

**Comment by jonbullock** [comment]
I've just checked out that branch and looked at the first occurrence of the NPE on 2008/04/frm-92101.html and the content file doesn't have any tags defined?

Because the post.gsp template doesn't perform a null check on line 37 there is an NPE.

**Comment by gilbertoca** [comment]
I didn't understand, why I need to do this in post template - there is no references to tag in it?

Just a little experiment:
mkdir default-jbake-folder
cd default-jbake-folder and jbake -i
edit jbake.properties, render.tags=true
edit second-post.md, removing tags=blog
run jbake
You will see:
´´´
19:58:11.347 INFO  org.jbake.app.Oven - Baking finished!
19:58:11.348 INFO  org.jbake.app.Oven - Baked 5 items in 9838ms
19:58:11.348 ERROR org.jbake.app.Oven - Failed to bake 1 item(s)!
Fev 17, 2015 7:58:11 PM com.orientechnologies.common.log.OLogManager log
INFORMAÇÕES: Shutting down storage: cache...
Fev 17, 2015 7:58:11 PM com.orientechnologies.common.log.OLogManager log
INFORMAÇÕES: Orient Engine shutdown complete

JBake failed with 1 errors:
1. Unable to convert object to String[]
´´´

**Comment by jonbullock** [comment]
My comment earlier was in relation to the branch you referenced. 

Your last issue (which uses the default templates) should be fixed in the next release. Just to check this, what version are you using for your experiement?

**Comment by gilbertoca** [comment]
I saw now! I'm sorry, I'm uncertain in choosing the template - Freemarker or Groovy. I will study them a little more before report a issue. Again, sorry for take you time.
I've used jbake-2.3.3-SNAPSHOTwith this script:
```
#!/bin/bash
mkdir default-jbake-folder
cd default-jbake-folder
jbake -i
sed -i 's/tags\=false/tags\=true/g' jbake.properties
sed -i 's/tags\=blog//g' content/blog/2013/second-post.md
jbake > jbake-b-v2.3.3.log
```

**Comment by jonbullock** [comment]
I tend to use Freemarker personally, only because it's what I have most experience with. If you have prior experience with a particular engine I would recommend you use that engine over others.

Hopefully I'll be able to get the next release out soon which will fix this issue.
