### ISSUE TITLE
Make the parsing metadata more flexible(intelligent)

### ISSUE THREAD

**Issue by gilbertoca** [jbake-org/jbake#180]
Currently the following header is not recognizable by jbake [1]:
```

title= Removendo alertas antigos da página principal do DBCONSOLE
date= 2007-10-08 14=22=17
type= post
status= publish
tags=
,Concurso Público
,Database
,dbconsole
,oracle
```
It complains about the following items:

1. the first line is blank
2. each field has white space after equal sign
3. the field tags is multi-line 

It would be good if it was more flexible. Maybe performing a trim after the equal sign and checking only the final value for correctness -in the multi-line case, concatenate all line.

[1] https://github.com/gilbertoca/gilbertoca.com/blob/d4d5e67b2b0db4dc8a7cf158bb7c6f0612e9ee88/src/jbake/content/2007/10/2007-10-08-removendo-alertas-antigos-da-pagina-principal-do-dbconsole.md

**Comment by jonbullock** [comment]
I agree the header code should be more tolerant of blank lines and spaces and this will be included in v2.5.0, but I don't agree with the multiline option support. The header is meant to be simple and concise.
