### ISSUE TITLE
renderTags replaces space by hyphen

### ISSUE THREAD

**Issue by gilbertoca** [jbake-org/jbake#181]
But template engine (freemarker) does not know about it - alltags, content.tags and tag_posts comes with space.
For now I've changed it locally:
```java
            //tag = tag.trim().replace(" ", "-");
            tag = tag.trim();
```

**Comment by jonbullock** [comment]
Hi Gilberto,

Any spaces in the tag are replaced with a dash purely for the rendering of the page for the tag. The data model should hold the un-modified tag value. Is this not the case?

**Comment by gilbertoca** [comment]
All tag link breaks - because ${tag} is the un-modified and the final URI generate by this method is contains the hyphen. So, you put the hyphen and I as final user have to remove them.

**Comment by jonbullock** [comment]
Ah in that case then I'll make sure the URI friendly (and modified) value is also available to the templates.
