### ISSUE TITLE
Improve i18n support of Jbake script

### ISSUE THREAD

**Issue by keilw** [jbake-org/jbake#182]
While Maven execute may actually allow this by passing necessary arguments to Maven, the jbake(.bat) scripts won't accept arguments like "-Duser.language=en". Thus by default calling these results in the OS language. If a user like myself works on a German OS, it may not be the preferred language for baking. Would it be possible to have the JBake script take optional arguments for language or country? (and if required variant)

**Comment by jonbullock** [comment]
Yeah sure, the execution scripts are pretty simple at the moment and could do with being enhanced.

**Comment by superjames** [comment]
I've got the same problem.
Writing an English blog on a French OS

**Comment by superjames** [comment]
setting the language in **jbake.properties** would be great

**Comment by keilw** [comment]
+1

**Comment by jonbullock** [comment]
The scripts generated by Gradle now allow you to define system properties via the JBAKE_OPTS environment variable. I'll create a separate issue to allow this to be set in jbake.properties as well for a future release.
