### ISSUE TITLE
Enhancement request to autobuild on new changes of the content files

### ISSUE THREAD

**Issue by sengopal** [jbake-org/jbake#183]
Static site generators such as Pelican has the ability to rebuild the content on changing the templates or the content. This is achieved using a gradle/grunt task which triggers the build on change of files.

**Comment by dknight** [comment]
Yes, would be nice to have autobuild option on file's change.

Like "jbake --autobuild"

I made own primitive hook based on the DirWatch (http://docs.oracle.com/javase/tutorial/essential/io/notification.html).

**Comment by jonbullock** [comment]
Until recently I hadn't fully understood how important this feature is. It'll definitely be moved up the priority list.

@dknight could you share a link to the hook you made?

**Comment by jonbullock** [comment]
Watch mode is part of the build in web server, so any change to a file will trigger the build process. It's best when used with incremental rendering.

**Comment by jonbullock** [comment]
Related issue that this fixes: jbake-org/jbake-gradle-plugin#14
