### ISSUE TITLE
Adding a <script> tag in GSP template gives "Failed to render archive"

### ISSUE THREAD

**Issue by sengopal** [jbake-org/jbake#184]
In the footer.gsp, adding a script tag with javascript, fails the render with error message

```javascript
<script>
		$(function() {
			hljs.tabReplace = "  ";
			hljs.initHighlighting();
		});
 </script>
```

```
8. Failed to render archive. Cause: org.jbake.template.RenderingException: groovy.lang.GroovyRuntimeException: Failed to parse template script (your template may contain an error or be trying to use expressions not currently supported): startup failed:
SimpleTemplateScript16.groovy: 19: illegal string body character after dollar sign;
   solution: either escape a literal dollar sign "\$5" or bracket the value expression "${5}" @ line 19, column 10.
   out.print("""js/highlight.min.js\"></script>

```

**Comment by jonbullock** [comment]
Thanks for reporting this, can I just confirm you were using the latest version of JBake, v2.3.2 ?

**Comment by sengopal** [comment]
Yes. 

± % gvm current jbake                                                                                                                                          
Using jbake version 2.3.2

**Comment by ancho** [comment]
you need to escape the $, because the SimpleTemplateEngine tries to interpret it as variable or expression.

\$function(.... works.

**Comment by jonbullock** [comment]
Thanks @ancho

**Comment by sengopal** [comment]
Thanks @ancho.That helped a lot.
