### ISSUE TITLE
Redundant slash in the Example Project Structures

### ISSUE THREAD

**Issue by dknight** [jbake-org/jbake#187]
The issue is pretty tiny and developer can easily fix it in templates, but hard to notice. I found it accidentally. When you download the package there is archive example_project_freemarker.zip

So sitemap.ftl and feed.ftl both use ${config.site_host} to generate URLs.

Sitemap doesn't contain a slash <loc>${config.site_host}${content.uri}</loc>
But Feed does <link>${config.site_host}/${post.uri}</link>

Some HTTP servers like Apache can 'eat' multiple slashes, but some HTTP servers will return 404 if there is double slash //.
Would be nice to update zip package, because really hard to notice it.

EDIT: As I see here https://github.com/jbake-org/jbake-example-project-freemarker it's fixed. But not it the package when you download it from jbake.org.

Sorry if I made too much text for this tiny issue.

**Comment by jonbullock** [comment]
Yeah I had noticed this and fixed it in the main repo for the Freemarker example project, I'll make sure this is included in the next release :)
