### ISSUE TITLE
Integrate with GVM Vendor API

### ISSUE THREAD

**Issue by marc0der** [jbake-org/jbake#189]
GVM now has an API that allows vendors like JBake to publish their own releases. A convenient Gradle plugin is also provided that does all the hard work for you.

It would be great to see JBake integrate with this API and managing their own releases.

**Comment by jonbullock** [comment]
That sounds excellent, where can I find information about the API?

**Comment by marcoVermeulen** [comment]
For sure, I've posted a blog explaining how it all works:
http://www.wiredforcode.com/blog/2015/03/26/the-gvm-vendor-api/

I will need to issue you with API credentials, you can contact me directly
to obtain those.

Give me a shout if you need any help with setting it all up.

**Comment by jonbullock** [comment]
Thanks Marco, I'll e-mail you to get some credentials.

Migrating to Gradle is on my to do list but quite far down at the moment, so I'll probably use the REST API for the next release.

**Comment by jonbullock** [comment]
Done as part of #280
