### ISSUE TITLE
Update docs for v2.4.0

### ISSUE THREAD

**Issue by jonbullock** [jbake-org/jbake#196]
Docs should include details on:

- [x] New template variable: baked_timestamp
- [x] JSON support in content metadata header 
- [x] Ability to specify path to use for new project initialisation
- [x] Ability to specify extension to be used when outputting content using custom templates (i.e. https://gist.github.com/jonbullock/5a380cf7f9a37a8cec48)
- [x] Output folder is located in source folder by default (https://github.com/jbake-org/jbake/pull/157)
- [x] Thymeleaf templates can also have .html extension
- [x] Ability to disable unwanted Markdown extensions
- [x] New configuration option: tag.sanitize

**Comment by jonbullock** [comment]
Also:

* New configuration option: asset.ignore

**Comment by jonbullock** [comment]
CLI init command now allows a folder to be specified, you can choose template engine using -t option.

**Comment by jonbullock** [comment]
Discussion & suggestions about how docs can be improved:

https://groups.google.com/d/topic/jbake-user/5-m4_3QAYjY/discussion

**Comment by jonbullock** [comment]
jbake/jbake.org#22

**Comment by jonbullock** [comment]
jbake-org/jbake.org#19

**Comment by jonbullock** [comment]
jbake-org/jbake.org#18

**Comment by jonbullock** [comment]
jbake-org/jbake.org#13

**Comment by jonbullock** [comment]
See commit jbake-org/jbake.org@31d90aff64e1f376713fc8848c2f678d047b137a

**Comment by ancho** [comment]
:+1:
