### ISSUE TITLE
Embedded Usage

### ISSUE THREAD

**Issue by sirinath** [jbake-org/jbake#201]
In instances where you want to dynamically generate web content, it would be good to use JBlake in embedded mode. 

It is possible to add support and API to use this as a library.

**Comment by jonbullock** [comment]
You can embed JBake and use it as a library today, the core is available on Maven Central. 

People have already developed Maven, Gradle & SBuild plugins using the current API.

**Comment by jonbullock** [comment]
The updated docs for 2.4.0 now has a section on how JBake can be embedded as a library:

http://jbake.org/docs/2.4.0/#use_as_libary

If there is any more info you require please let me know so I can get it added to the documentation.
