### ISSUE TITLE
Scripting and Expression Language Support

### ISSUE THREAD

**Issue by sirinath** [jbake-org/jbake#202]
It is possible to support expression language and scripting support to dynamically generate the mark up docs and then process.

This will be very useful for: https://github.com/jbake-org/jbake/issues/201

**Comment by jonbullock** [comment]
Could you elaborate on this a bit further? There is nothing stopping you using any scripting language you like today and dynamically generating the content files for processing by JBake using the API today.

**Comment by sirinath** [comment]
E.g. something like
```
<% for (int i = 1; i < 4; i++) { %>
 - Item i
<% } %>
```

in a supported scripting language. Groovy, Scala, are ideal choices for initial support.

**Comment by jonbullock** [comment]
Groovy is already supported as a template engine and enables code like you've shown. There is also a comprehensive data model that is exposed to the template engines too.

**Comment by jonbullock** [comment]
Here's the link to the example project that includes some Groovy templates: https://github.com/jbake-org/jbake-example-project-groovy

There is also more details on the data model exposed in the updated docs: http://jbake.org/docs/2.4.0/#data_model

Does this cover your requirements?
