### ISSUE TITLE
OrientDB appears to be logging separately and isn't controlled via logback.xml

### ISSUE THREAD

**Issue by jonbullock** [jbake-org/jbake#205]
23:04:53.628 INFO  org.jbake.app.Oven - Baked 40 items in 5280ms
May 17, 2015 11:04:53 PM com.orientechnologies.common.log.OLogManager log
INFO: Shutting down storage: cache...
May 17, 2015 11:04:53 PM com.orientechnologies.common.log.OLogManager log
INFO: Orient Engine shutdown complete

**Comment by ancho** [comment]
Hi,

there are different legacy bridges for slf4j. See http://www.slf4j.org/legacy.html

The jul-to-slf4j bridge could be used to bridge the logging from OrientDB as it uses the java.util.logging framework.
