### ISSUE TITLE
Index page for "tags"?

### ISSUE THREAD

**Issue by uli-heller** [jbake-org/jbake#211]
I'm not sure, maybe I'm missing something so this is potentially just an issue of my understanding...

I'm trying to use "render.tags" in the protoype of my blog. It seems to work quite OK, but somehow I'm missing something like a "landing page" or an index. My "idea" is this:

* you have a menu item called "tags"
* when you click on it, you're landing on an index page showing all available tags
* from there, you can jump to a specific tag
* from there, you can jump to a specific blog entry / article

I've looked at various [sites using jbake](http://jbake.org/community/sites.html), some of them do use tags
but with a hard-coded menu containing the tags (http://melix.github.io/blog/, http://jdpgrailsdev.github.io/blog/).

For me, the "landing page" should look similar to:

```
<h2>Tags:</h2>
<% alltags.collect{it-> [it.toLowerCase(), it]}.sort{it-> it[0]}.each { lc, tag ->%>	
         <a href="${tag}.html">${lc}</a> 
<%}%>
```

Now my questions:

* Am I missing something? Does a feature like this already exist?
* What's the best way to implement this? For me, it would be ideal to dynamically create an "index.html" underneath the "tags" folder...
* My current workaround is to
    * extend the tags template to add all tags on every tag page (similar to http://melix.github.io/blog/)
    * at a well-known tag "jbake" and use this as a landing page
    * link the "tags" menu entry to .../tags/jbake.html
* I'm not happy with the work around, so I might create a pull request for the tags index page in case others like to see this as well...

Thanks + best regards, Uli

**Comment by jonbullock** [comment]
The tag support provides a rendered page per tag used but it doesn't currently provide an index page for the tags. However this is possible by using the custom template support - http://jbake.org/docs/2.4.0/#custom_templates

If you create a content file in your /tags folder called index.html and give it a metadata header such as:

    title=Tags Index
    date=2015-06-07
    type=tagindex
    status=published
    ~~~~~~

This file doesn't need any content in it as it is only there to trigger the rendering using a new template file. Next add the following line to your `jbake.properties` file:

    template.tagindex.file=tagindex.gsp

Then create your template file in /templates called `tagindex.gsp` and utilise the tag data model - http://jbake.org/docs/2.4.0/#global - as you require.

Let me know how you get on.

Regards,
Jon

**Comment by uli-heller** [comment]
Hi Jon,

your proposal works absolutely fine!

Thanks a lot, Uli

Am 07.06.2015 um 19:27 schrieb Jonathan Bullock:
>
> The tag support provides a rendered page per tag used but it doesn't 
> currently provide an index page for the tags. However this is possible 
> by using the custom template support - 
> http://jbake.org/docs/2.4.0/#custom_templates
>
> If you create a content file in your /tags folder called index.html 
> and give it a metadata header such as:
>
> |title=Tags Index
> date=2015-06-07
> type=tagindex
> status=published
> ~~~~~~
> |
>
> This file doesn't need any content in it as it is only there to 
> trigger the rendering using a new template file. Next add the 
> following line to your |jbake.properties| file:
>
> |template.tagindex.file=tagindex.gsp
> |
>
> Then create your template file in /templates called |tagindex.gsp| and 
> utilise the tag data model - http://jbake.org/docs/2.4.0/#global - as 
> you require.
>
> Let me know how you get on.
>
> Regards,
> Jon
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/jbake-org/jbake/issues/211#issuecomment-109778650>.
>


-- 
Uli Heller

daemons point Gesellschaft für Datenverarbeitung mbH
Zahn-Nopper-Straße 1-3, 70435 Stuttgart
Internet: www.daemons-point.com
Tel:+49 711 806708 0, Fax: +49 711 806708 19
mailto:uli.heller@daemons-point.com

Geschäftsführer: Steffen Walter, Uli Heller
Sitz der Gesellschaft: Stuttgart
Amtsgericht Stuttgart, HRB 22333

**Comment by uli-heller** [comment]
Thanks, I'm closing the issue....

**Comment by jonbullock** [comment]
Glad to hear it, I'll make sure this scenario is covered by the docs in case somebody else wants to achieve the same goal.
