### ISSUE TITLE
tag_posts: Contains draft posts as well as published posts

### ISSUE THREAD

**Issue by uli-heller** [jbake-org/jbake#213]
I believe there is an error within "tag_posts". From what I understand, only published posts are supposed ton show up within the list. Unfortunately, draft posts seem to show up, too. This leads to broken links.

For me, a simple change to ContentStore.java seems to fix the issue.

The version I used is 2.4.0.

```diff
diff --git a/src/main/java/org/jbake/app/ContentStore.java b/src/main/java/org/jbake/app/ContentStore.java
index d7074d7..f7bd679 100644
--- a/src/main/java/org/jbake/app/ContentStore.java
+++ b/src/main/java/org/jbake/app/ContentStore.java
@@ -94,7 +94,7 @@ public class ContentStore {
     }
 
     public List<ODocument> getPublishedPostsByTag(String tag) {
-        return query("select * from post where status='published' where ? in tags order by date desc", tag);
+        return query("select * from post where status='published' and ? in tags order by date desc", tag);
     }
 
     public List<ODocument> getPublishedPages() {
```

I'll create a pull request for this... #214 
Maybe it was a bad idea to create an issue AND a pull request, the pull request is probably sufficient...

**Comment by jonbullock** [comment]
Thanks for taking the time to raise this issue.
