### ISSUE TITLE
Slim (http://slim-lang.com/) Support

### ISSUE THREAD

**Issue by sirinath** [jbake-org/jbake#215]
Through JRuby maybe you can support this also.

**Comment by jonbullock** [comment]
That template engine is a Ruby based one and requires some lower level Ruby frameworks (Temple & Tilt) before support could be added. Some initial investigation on how to use Tilt via Java was done under the AsciidoctorJ project but ran into some significant hurdles. So it's unlikely we'll support that engine any time soon.

However if you want a template engine like that you should look at the Groovy MarkupTemplateEngine - http://docs.groovy-lang.org/docs/groovy-latest/html/documentation/markup-template-engine.html

Support for this engine will be coming in 2.5.0 (see PR #185).

**Comment by sirinath** [comment]
When will 2.5 come out?

**Comment by jonbullock** [comment]
No date scheduled yet but I'm hoping within the next 4-8 weeks.
