### ISSUE TITLE
Document representation in JBake

### ISSUE THREAD

**Issue by haumacher** [jbake-org/jbake#221]
Hi,

having studied some of the JBake code, I've the following question: After parsing the page source from the `content` folder and before baking, documents are internally represented as `ODocument` instances and stored in an OrientDB graph database. In the default configuration, this database is kept in memory only - created when JBake is started and dropped when the VM exists after baking all documents.

Is there a scenario, where its could be useful to store this database on disk and keep it between multiple invocations of JBake?

Best regards
Bernhard Haumacher

**Comment by jonbullock** [comment]
Hi Bernhard,

The persistent store is to enable incremental rendering, so only content that has added or changed is baked. The store provides the reference to check content against.

Config option to enable persistent store: http://jbake.org/docs/2.4.0/#persistent_content_store_path

Jon
