### ISSUE TITLE
Move to Java 8 for v2.5.0 or v3.0.0

### ISSUE THREAD

**Issue by msgilligan** [jbake-org/jbake#224]
By its nature JBake is a standalone tool installed on an individual machine that generates static output that is pushed to the server. So there's little worry about runtime requirements other than in the build tools themselves. Java 7 is reaching end-of-maintenance (or whatever Oracle calls it) and Java 8 offers significant improvements.

I see no reason not to move to Java 8 for v2.5.0, but at the very least v3.0.0 should use it (and skip Java 7)

This issue started out as a comment on Issue #107, but I thought it should be a new, separate issue. Java 8 has been adopted very rapidly in the 16 months since that issue was created and we should consider moving to it as quickly as possible.

**Comment by jangalinski** [comment]
+1

**Comment by jonbullock** [comment]
Absolutely fine with me, I'll give the community chance to voice any concerns on the other thread before closing it in favour of this.

**Comment by melix** [comment]
Just to make it clear : as soon as you require 1.8, you force all
downstream apps that integrate JBake to upgrade. It means the Gradle plugin
as well as the maven one. It's not necessarily a good thing.

Your call anyway.
Le 16 août 2015 21:08, "Jonathan Bullock" <notifications@github.com> a
écrit :

**Comment by haumacher** [comment]
For JBake users, there is no benefit when increasing the minimum Java compatibility level. Currently built against Java 6, JBake should be runnable on any Java 6, Java 7 and Java 8 VM (if that's not the case it's an issue that should be fixed). 

When compiling against Java 8, you require a Java 8 VM for runtime. The only benefit upgrading the JVM version is the possibility to uses Java 7 or Java 8 language features for development, e.g. try with resource, simplified type parametrization or lambda expressions. While this might slightly simplify the code here and there, I think it's not worth breaking the compatibility to embedding apps that cannot upgrade to Java 8 in the near future.

**Comment by msgilligan** [comment]
>  the possibility to use Java 7 or Java 8 language features for development

This is a huge advantage to the project IMO.

> compatibility to embedding apps

Aside from the Gradle and Maven plugins (which should be straightforward to upgrade) what embedding apps are there? @haumacher Do you have a specific embedding app in mind?

My impression is that JBake is used on individual machines to generate static sites and is not embedded in complex server applications which are slow to upgrade. It would be great to see JBake have the cleanest, most modern code base possible and to favor rapid development to better compete with the Node based ecosystem and to attract more contributors and more eyeballs on the code.

**Comment by melix** [comment]
@msgilligan Straightforward to upgrade doesn't mean that it's good to do: it means that your complete build has to upgrade to Java 8. This is not something all projects want. With Gradle we can conditionally apply the plugin based on the JVM running, not sure it's doable with Maven. And why do we conditionally apply? Well, for Groovy (disclaimer: Groovy doesn't use JBake), we make sure the project compiles and executes fine on JDK 6 to 9. So requiring a minimal runtime version definitely has stronger implications.

**Comment by msgilligan** [comment]
As you say, @melix , Groovy is not using JBake. It seems that most (all?) sites using JBake are standalone builds (e.g. not mixed in with a complex build like the Groovy project) Your concerns would be valid for other build tools, as they are for Groovy and Gradle themselves, but as all the JBake sites I've seen are standalone builds of blogs this doesn't seem like much of an issue.

@jonbullock You probably know the users best -- are people using the Gradle or Maven JBake plugins integrated in with complex builds?

**Comment by haumacher** [comment]
@msgilligan Personally, I just started using JBake for a small standalone site project and therefore have no concerns upgrading to any Java version around. But I could imagine that JBake could be used building e.g. the documentation of any other software project. The build of such project would then naturally become an embedding app.

**Comment by lefou** [comment]
From a JBake developer perspective I like the move to Java 8 as all these cool new language features are available. As JBake user and integrator I don't like it, as you force user to run on Java 8 which is often not that simple in existing projects. Also you force various build integrations like Maven, Gradle, SBuild to run on Java 8. I can see a clear tendency in JBake to be used a library, and as such we should aim to be as compatible as possible.

Of course there is no black or white. In various projects I used mixed approach as follows:
* Java 8 source language features and compiler
* **BUT** no Java 8 API, instead use some small helper tool like https://github.com/lefou/de.tototec.utils.functional or provide some basic helper classes that provide nice lambda API aroud Java 7 collections
* postprocess the class files with retrolambda to produce a Java 7/6 compatible library

With such an approach, you can provided a Java 7/6 API and runtime but use Java 8 internally. Of course, this adds some complexity to the build setup, but mature Maven plugins already exist. 

So, there is a way use Java 8 language but still provide Java 7 API and runtime. **My main point is to keep Java 7 support.** The Java 8 story is only to make those devs happy that want to use Java 8 today.

**Comment by mperry** [comment]
@lefou The Functional Java project uses this approach (note that I am the main contributor).  We use the gradle retro lambda plugin to use lambdas with the library (compiling with Java 8), but target the JVM 7 runtime, see http://www.functionaljava.org/.

At some point though you need to move to Java 8.  The Java 7 runtime is past end of life and Java 8 has been released for over a year.  If not now, then when?

**Comment by lefou** [comment]
@mperry JBake is pretty stable and runs with older and newer JVMs. I fail to see the benefits in excluding those users still forced to run on older JVMs just because we can. Of course this position may change in future, but currently I too often have to work in such old environments myself. And of course I want to use my beloved open source project in those environments. I tried to show a way to move forward without loosing part of the community.

**Comment by msgilligan** [comment]
Here's a specific question: *Does anyone know of a site on the list [Sites Using JBake](http://jbake.org/community/sites.html) that could not easily be updated to use Java 8?*  (Assuming, of course that the Maven and Gradle plugins were also updated to Java 8) What about Java 7?

This has largely been a theoretical discussion. What are our current users using? Can they upgrade? New users and new projects are even more likely to be able to work with newer VMs. As far as I can tell from the above, not one person has said "moving to Java 8 will break the build of *my* site.)

I'm playing devil's advocate here by pushing for Java 8, but I definitely understand the arguments against doing so. Personally, I would like to see JBake evolve quickly and attract the most/best developers. Using Java 8 is a good way to encourage this and to make working on the project more fun. In the face of *data* that users can't or won't upgrade to Java 8, then maybe we should use Java 7 instead, or stick with Java 6.

**Comment by haumacher** [comment]
From the Sites Using JBake: "CRaSH the shell for the Java Platform" is building in a Java 6 compatible way. Requiring Java 8 for building the site would at least be inconvenient.

**Comment by msgilligan** [comment]
I just built [crashub.github.com](https://github.com/crashub/crashub.github.com/tree/site) with Java 8 and it worked fine. Assuming the Maven plugin is also updated to Java 8, I don't see anything in the `pom.xml` that would be an issue. Am I missing something?

2 cool things about your site:

1. It has the most original styling (biggest changes from default template) of any JBake site I've seen.
1. It's interesting how you are pulling `.zip` files of JavaDoc, reference manuals, etc from Maven and unzipping as part of the publishing process.

**Comment by haumacher** [comment]
Hey, CRaSH it's not *my* site - I just picked an arbitrary project from "Sites Using JBake" that looks like providing a library module and checked, if *they* keep Java 6 compatibility by looking at their pom.xml.

Even if it may be possible keep Java 6 compatibility even when using a Java 8 runtime for the build process - the most safest way to do this is using a native Java 6 runtime environment... But this is not possible - or at least inconvenient - if one of the build stages requires Java 8.

**Comment by msgilligan** [comment]
Well every JBake project that I have seen (admittedly, I've only looked at about 10 -- including CRaSH) use a separate repo and build for the the JBake site than for the project code. So, just because the code builds with Java 6, doesn't mean that the JBake site needs to.

(CRaSH is interesting because it imports documentation artifacts from the project build via Maven .zip artifacts -- an approach I may adopt as I get further along on my documentation projects. This is a good approach because it makes it possible to host documentation from multiple versions of the project on the same site.)

The usage pattern for JBake seems to be for a separate standalone build, that is why I think that moving to Java 8 is (likely) not a real issue for this community. Part of this usage pattern is because GitHub user/organization pages require a separate repo for the content and there's a strong convention to put the source on a branch within this same repository. (The convention is because of built-in support for Jekyll, there's not reason things *must* be done that way, but it is definitely a convention/pattern.)

**Comment by jonbullock** [comment]
Apologies that I've been slow to respond to this thread, and thank you to everyone who has contributed so far, the debate is exactly what I was hoping for.

I echo the sentiments of @lefou as a dev I'd love to take advantage of Java 7/8 features but I'd prefer not to do this if it means it causes issues to certain members of the community. I do feel a certain obligation to users who have adopted JBake so far. Having said that a line has to be drawn somewhere in terms of supported platforms.

As mentioned there are other ways to take advantage of the new language features... of which Groovy is one I have thought about many times. I've also been looking at how the Spring framework provide support for the various Java versions too.

Moving forward I'll try and get more input into the debate from those users who I know use JBake in more integrated ways. 

The most important take away for me is that, whatever direction we go in, a clearly communicated and documented plan in terms of supported Java versions is required.

**Comment by lefou** [comment]
Before we consider to proceed future development in Groovy, which would clearly exclude way more users/devs than the switch to Java8, I would be interested in the sensed gain of Java8 syntax vs. the Java8 API. If it is Java8 syntax we strive for, we could immediately switch, but compile to older bytecode with retrolambda. If it's the API, then downgrading the bytecode will not work. 

Sorry, if I repeat myself here. I'm all for the former approach, as long as we see it as some intermediate solution. We need to rethink it next year or next release and drop it when there is no longer a demand. Though, to feel the syntax fun, we need to add some Java7 compatible functional API like functional-java (which comes with it's own immutable collections; does that work with Groovy?) or utils.functional or anything else.

**Comment by msgilligan** [comment]
The problem with using Groovy to develop a library is that you create a dependency on the Groovy runtime. The Groovy runtime includes an implementation of the MOP (Meta-Object Protocol) And, as I understand it, there is no guarantee of MOP interoperability between different versions of Groovy.

You'll find that the most popular Groovy projects (e.g. Grails, Gradle) are not distributed as libraries but as complete frameworks with a bundled version of Groovy.

@melix Is that a fair and concise description of the issue?

**Comment by jonbullock** [comment]
I fear I've confused matters by mentioning Groovy, please don't read too much into my statement, I'm not planning on switching over to Groovy for JBake. 

In terms of the Java 8 syntax/API I can't really comment right now as I don't have any use cases or experience to base my comments on, however being able to use Java 8 syntax without requiring Java 8 does appeal to me.

However in terms of Java7 API, I am looking to use the NIO.2 API in JBake to add watch mode support.

**Comment by melix** [comment]
@msgilligan This is *almost* fair to Groovy. While it does come with a runtime, we **do** make guarantees with regards to interoperability. Groovy is backwards compatible, and sometimes (using the compat jar) forward compatible. Breaking changes are planned for Groovy 3, which is not due anytime soon.

**Comment by ieugen** [comment]
@jonbullock Watch wupport would definitly be nice. I've put some projects in production and I agree that you should be carefull what versions you require. My opinion is that bumping minimum version to 1.7 is ok since it's now the default in many operating systems (Debian Jessie and derivatives, Ubuntu, etc.). 
Jbake is also mostly used as a end user tool so you won't have other projects depending on it. Also, I imagine that most of the time you build your website locally and push the changes to production.

Regards,

**Comment by jonbullock** [comment]
Thanks for the feeback @ieugen 

Could I ask everyone to complete this form: http://goo.gl/forms/YhPww3UyQE

**Comment by bodiam** [comment]
I hope that for 3.0.0 we could move to Java 8. I think that also goes nice with semantic versioning, and shows that things can (and possibly will) break. Is there are any insight in the poll already?

**Comment by jonbullock** [comment]
Out of 36 responses so far, all 36 were OK with a move to Java 7 and 31 were OK with a move to Java 8.

**Comment by manikmagar** [comment]
May be late in the party but just wanted to add, I am baking my sites with JBake v2.4.0 and Java 8.

**Comment by obfischer** [comment]
We have to differ between Java 8 as possible runtime environment and using Java 8 language features.

**Comment by jonbullock** [comment]
Just posted to the dev mailing list about this, proposed roadmap is:

- v2.6.0 onwards will require Java 7 runtime
- v3.0.0 onwards will require Java 8 runtime

Please post on the mailing list if this poses a problem.
