### ISSUE TITLE
Support for Cygwin

### ISSUE THREAD

**Issue by abelsromero** [jbake-org/jbake#225]
This is not a big issue, but this request aims to offer a nice first time experience to cygwin users.
To use jbake with cygwin, you have to give exec permissions to the jbake.bat command. But then when you use `tab` to autocomplete the command both `jbake` and `jbake.bat`.
You can also do other changes to end with a clean jbake command, but it's a p*** .

I found that this can easily fixed replacing the main jbake command like this:
```
#!/bin/bash
EXEC_LOC="`dirname "$0"`"
EXEC_PARENT="`dirname $EXEC_LOC`"
if [ `uname -o` = "Cygwin" ]
then
    java -jar $(cygpath -w "${EXEC_PARENT}/jbake-core.jar") $@
else
    java -jar "${EXEC_PARENT}/jbake-core.jar" $@
fi
```

**Comment by jonbullock** [comment]
Thanks for the suggestion, I'll include this in the v2.5.0 release.
