### ISSUE TITLE
Improve exec scripts to pick up all jar files in /lib

### ISSUE THREAD

**Issue by jonbullock** [jbake-org/jbake#230]
Improve exec scripts to pick up all jar files in /lib

See here for context: https://twitter.com/bobbytank42/status/564066267645378560

**Comment by jonbullock** [comment]
Wildcards isn't supported when using manifest classpath, need to set classpath in exec script as wildcards are allowed here.

**Comment by ancho** [comment]
At what location is the lib/ directory expected? Relative to the root project? Or is it the lib directory of the distribution?

**Comment by jonbullock** [comment]
It's the /lib directory of the distribution.

**Comment by jonbullock** [comment]
@ancho are you working on this? Or did I read your comment in #381 wrong?

**Comment by ancho** [comment]
Jep. I'm on it..
