### ISSUE TITLE
Add a code of conduct to the project

### ISSUE THREAD

**Issue by jonbullock** [jbake-org/jbake#232]
Potential solution: http://contributor-covenant.org/

**Comment by msgilligan** [comment]
Shouldn't a code of conduct be about behavior and not ideology and restricting speech? Is JBake '"culturally inappropriate"? Maybe not this week, but who knows about next week?

**Comment by jonbullock** [comment]
Doesn't that proposed code define what behaviour is expected and what behaviour isn't acceptable? I assume you're not in favour of having a code at all...?

**Comment by msgilligan** [comment]
Yes, but it's vague and over-reaching (in my opinion) and smells (to me) of political correctness, cultural marxism, and restriction of speech*. Ultimately, I'd hold my nose and agree to it, but I don't like it. Most of codes-of-conduct that I've seen have the same issues, but I haven't searched for alternatives.

JBake seems to me like a well-run and inclusive project. I'm new to it and started a controversial discussion where I took an almost devil's advocate position of pushing JDK 8 for the next release and the discussion was very good, I thought.

Have there been issues on this project? Has anyone complained to you? Ultimately the project leaders are responsible for setting the tone for the community and keeping discussions professional. I don't feel a CoC is necessary for this project and if you must choose one, I'd prefer one with the PC toned down a little bit.  (I hear that at some colleges just saying "PC" is now considered a micro-agression, so apologies if I've offended anyone. haha.)

Those are my thoughts. Not a huge issue for me, I know that I'll behave professionally and respectfully either way, but if I get a vote -- I vote against that particular CoC.

**Comment by bodiam** [comment]
Oh, seriously? I'm really with @msgilligan here. I am really not a fan of this. Actually, I had never heard of a CoC for Open Source projects, and I don't support such a thing at all. I cancelled my registration for a conference which had a similar CoC, and I will not support a framework which actively promotes such a thing.

**Comment by jonbullock** [comment]
Wow I had no idea people felt this strongly about this, I genuinely thought this would be a positive thing, but if it not seen that way there is no point.

Thanks for taking the time to share your views on this matter.

**Comment by msgilligan** [comment]
@jonbullock Your heart is in the right place. JBake seems to have a great community. As long as it stays that way, there's nothing to worry about.

**Comment by bodiam** [comment]
@jonbullock It goes a bit to far to tell your here why I feel like this. I understand your intentions are good, no doubt about that, I'm just not sure if this is the right approach. Thanks for your consideration!

**Comment by haumacher** [comment]
+1
