### ISSUE TITLE
Empty output.extension causes NPE

### ISSUE THREAD

**Issue by puredanger** [jbake-org/jbake#234]
The commit:
https://github.com/jbake-org/jbake/commit/17a4372bd3275e2b74f11f811da71b94ce5bae76
for issue #233 causes NPEs on baking:

java.lang.NullPointerException: null
	at org.jbake.app.Renderer.createWriter(Renderer.java:104) ~[jbake-core.jar:na]
	at org.jbake.app.Renderer.render(Renderer.java:90) ~[jbake-core.jar:na]
	at org.jbake.app.Oven.bake(Oven.java:157) ~[jbake-core.jar:na]
	at org.jbake.launcher.Main.bake(Main.java:50) ~[jbake-core.jar:na]
	at org.jbake.launcher.Main.run(Main.java:86) ~[jbake-core.jar:na]
	at org.jbake.launcher.Main.main(Main.java:36) ~[jbake-core.jar:na]

Run with master at the point of the commit above. To reproduce:

jbake -i foo
cd foo
modify jbake.properties to include "output.extension="
jbake -b

**Comment by jonbullock** [comment]
Thanks for reporting this... I'll commit a fix shortly, a workaround is to fully quality the source and destination folders while baking. I was testing last night using fully qualified paths!

**Comment by puredanger** [comment]
That does seem to fix that issue, however xref links from asciidoc source files seem to still be rendered with the .html extension, so all cross-doc links are broken. 

I really appreciate you looking at this by the way, and I'm sorry to be whack-a-mole'ing you with problems like this. Thank you for all the work on JBake - it's so very very close to exactly what I need.

**Comment by jonbullock** [comment]
Ah I have a suspicion that Asciidoctor is assuming that the output files will always have a .html file extension which is causing the problem with xref's. Let me do some digging...

Thanks for the feedback... I've been reading your blog for a number of years so it's great to see you using my humble little tool!

**Comment by puredanger** [comment]
Working on an overhaul for a very visible site with jbake... stay tuned. :)

**Comment by jonbullock** [comment]
Excellent!

Looks like you can control the file default suffix using the `outfilesuffix` attribute: http://asciidoctor.org/docs/user-manual/#navigating-between-source-files

Whether it allows an empty value though is a different matter...

**Comment by puredanger** [comment]
That works!

I was able to get everything working by setting the following properties in jbake.properties:

```
output.extension=
outfilesuffix=
asciidoctor.attributes.export=true
```

**Comment by jonbullock** [comment]
Excellent, I'll be sure to include details on how to achieve this goal in the docs.
