### ISSUE TITLE
Transfer ancho/jbake-example-project-groovy-mte to jbake-org and integrate with distribution

### ISSUE THREAD

**Issue by ancho** [jbake-org/jbake#244]
In order to provide an example project for Groovy MarkupTemplateEngine templates, introduced with #185, move https://github.com/ancho/jbake-example-project-groovy-mte to jbake-org organization.

Provide an assembly description and checkout the example project analog to the other example projects.

**Comment by jonbullock** [comment]
I notice you've used Foundation in the example project, any particular reason why?

**Comment by ancho** [comment]
No. Not really. I just decided to give foundation a try while designing my blog.
I consider to change the style back to jbake style to give it something like an identity.
What do you think?

**Comment by jonbullock** [comment]
That's not necessary at the moment. The goal of the example projects is to give the end user a starting set of templates for the relevant template engine, they are not meant to be the finished article in terms of design.

You should be able to transfer the repo into the organisation now, let me know if you have any issues as I never remember how to enable this in GitHub.

**Comment by ancho** [comment]
Thank you @jonbullock! I created a new Repository and pushed mine to the new one.

**Comment by jonbullock** [comment]
Excellent 👍
