### ISSUE TITLE
setting asciidoctor.option.template_dirs in jbake.properties causes an error

### ISSUE THREAD

**Issue by mtolk** [jbake-org/jbake#252]
I'm using asciidoc document in JBake to generate my website.
I want to make some changes to the HTML asciidoctor generates so I wanted to use the template_dirs option.

Doing this gives an error:

    An unexpected error occurred: (NoMethodError) asciidoctor: FAILED: : Failed to parse source,     undefined method `each' for "src/custom-asciidoctor-backends/erb/html5":String

I think I figured out what the problem is.
When you pass the option template_dirs asciidoctor expects a List.
JBake tries to guess the required object using the AsciidoctorEngine.guessTypeByContent() method,
but that method has no support for Lists, just String, Boolean and Number.

So the option template_dirs  is passed to Asciidoctor as a String which causes the error inside asciidoctor.

**Comment by jonbullock** [comment]
Thanks for raising this @mtolk we'll aim to fix this in the v2.5.0 release.
