### ISSUE TITLE
org.jbake.app.template.FreemarkerTemplateEngineRenderingTest.renderPost fails when non-English locale is used

### ISSUE THREAD

**Issue by iryndin** [jbake-org/jbake#259]
Unit test `org.jbake.app.template.FreemarkerTemplateEngineRenderingTest.renderPost` fails when non-English locale is used. This is because FreeMarker uses local locale to render date strings, while unit test have hardcoded date string in English, which leads to failure. 

How to fix: do not hardcode date strings in unit tests, instead use generated date strings (e.g. with `SimpleDateFormat`).

**Comment by iryndin** [comment]
here is pull request: https://github.com/jbake-org/jbake/pull/260

**Comment by jonbullock** [comment]
Thanks for raising this, I'm thinking that the locale used by template engines should be explicitly set, there is already code in place to allow the locale to be set for Thymeleaf. We can always fall back to the default if one isn't set explicitly.
