### ISSUE TITLE
Two tests fail on Windows

### ISSUE THREAD

**Issue by buumi** [jbake-org/jbake#261]
copyIgnore and testWriteProtected fail on Windows systems. I guess that's because on Windows .test.txt is not considered hidden. Also readOnlyFolder.getRoot().setReadOnly() doesn't work on Windows. Please close this if it's not even intented to work on Windows.

**Comment by jonbullock** [comment]
Thanks for raising this issue.

**Comment by jonbullock** [comment]
Fixed when #229 was merged in.
