### ISSUE TITLE
Upgrade Thymeleaf to 3.0

### ISSUE THREAD

**Issue by oliverlietz** [jbake-org/jbake#262]
Thymeleaf `3.0.0.BETA01` is available, see [Thymeleaf 3 five-minute migration guide](http://www.thymeleaf.org/doc/articles/thymeleaf3migration.html) also.

**Comment by jonbullock** [comment]
Thanks for opening this issue, I normally review and upgrade dependencies prior to each release but this will serve as a reminder. 👍

**Comment by jonbullock** [comment]
Dependency updated... see #263
