### ISSUE TITLE
Update documentation section about GVM

### ISSUE THREAD

**Issue by rlovtangen** [jbake-org/jbake#265]
GVM has been renamed to SDKMAN. See http://sdkman.io/
Update section `1.3 GVM` in the docs accordingly.

The command to install jbake with SDKMAN is
````
sdk install jbake
````

**Comment by jonbullock** [comment]
Thanks for highlighting this.

**Comment by rlovtangen** [comment]
Glad to help. Sorry for using wrong repo.

**Comment by jonbullock** [comment]
Don't worry about it, the documentation shouldn't really be in the site repo but it's a low priority for me at the moment to change this.

**Comment by jonbullock** [comment]
Now fixed in site repo.
