### ISSUE TITLE
"alltags" does not contain tags from custom template types

### ISSUE THREAD

**Issue by mkobit** [jbake-org/jbake#266]
I was looking to use JBake and Freemarker to generate a static site and use my own custom templates for rendering certain pages, rather than using `post` and `page` as those do not have semantic maening in the site I am generating. 

The query `query("select tags from post where status='published'")` is run when trying to retrieve `"alltags"`, and from what I have discovered a table is created for each `"docType"`. It was a little strange to me that the "global" values are not necessarily collected from all types.

**Comment by oliverlietz** [comment]
@mkobit I'm interested in this _feature_ also. Do you have a patch to take tags from all types into account?

**Comment by jonbullock** [comment]
Thanks for raising this issue.
