### ISSUE TITLE
Allow gemPath to be specified for the AsciidoctorEngine

### ISSUE THREAD

**Issue by aalmiray** [jbake-org/jbake#267]
The current `AsciidoctorEngine` does not allow passing a `gemPath` option to the `Asciidoctor.Factory.create()`. This option is needed to enable additional functionality such as `asciidoctorj-diagram`.

**Comment by aalmiray** [comment]
I can confirm with a quick "hack" that enabling `gemPath` and `requires` to be set on the `Asciidoctor` instance does allow diagrams to be rendered in a baked content. We'll have to wait for asciidoctor-1.6.0 to be released (and its companion asciidoctorj release) in order to avoid reflective calls to protected fields in `Asciidoctor`.

**Comment by jonbullock** [comment]
:+1:
