### ISSUE TITLE
Question: running jbake with spring(boot) - experiences?

### ISSUE THREAD

**Issue by jangalinski** [jbake-org/jbake#277]
I am planning to use jbake as a static site generator that aggregates data from lots of sources (file system, database, social sites, ...) so I will do a lot of coding around the pure baking process. I would like to use spring boot for that application so I can stick with the DI pattern and use all the tools the platform provides.

I wonder if someone did this before and if there are any pitfalls to expect? What would be your prefered approach to integrate jbake-oven in an application? Just a piece of code call in the main method after everything else has been prepared? Not even code but only orchestrate via maven plugin chaining? Glad for any hint. Thanks.

**Comment by luistrigueiros** [comment]
Hi,

I recently implemented JBake with spring boot you can see the source code at:
https://github.com/southcitychurch/scc-web

**Comment by volyx** [comment]
@luistrigueiros nice work!

**Comment by jangalinski** [comment]
Nice work in deed, but you misunderstood my approach: you use gradle to bake your static site and then put a spring boot application aside this static content to let it run on openshift and offer some dynamic features like mail-form.

What I want to do is use a spring-boot application to bake the site, and collect the dynamic data while doing so. 
For example: read latest post from facebook and twitter , put them jbake src and then build the static page using the api http://jbake.org/docs/2.4.0/#api

**Comment by luistrigueiros** [comment]
Hi Jan,
Thank you.
From what I experienced there is there is a problem with JBake cache when
you try the second run and it has to do with the access to the underline
database that implements the caching orientdb, I think you will get this
error probably.
I read in the issue that this is fixed in the 2.5.0 snapshoot.

**Comment by jonbullock** [comment]
@jangalinski I'm not aware of anyone who has done something similar but your best source for using the JBake API are the Maven & Gradle plugins for JBake.
