### ISSUE TITLE
custom types are broken

### ISSUE THREAD

**Issue by ancho** [jbake-org/jbake#283]
While integrating the groovy-mte example project (see #282) I stumbled upon a problem with custom templates/types.

They are not recognized anymore and are not accessible within the templates.

The new document type is added to the ```DocumentTypes```. It seems to be connected with the ModelExtractors mechanism. There is no registered model extractor for the new custom type.

Maybe the _[should never happen](https://github.com/jbake-org/jbake/blob/master/src/main/java/org/jbake/template/GroovyMarkupTemplateEngine.java#L78)_ part happened ;)

Needs more investigation.

**Comment by jonbullock** [comment]
Thanks for raising this, I'll double check.
