### ISSUE TITLE
Permlinks, Categories and Pagination?

### ISSUE THREAD

**Issue by manikmagar** [jbake-org/jbake#284]
First of all thank you for making JBake, Its awesome 👍 

I am creating my personal blog but have few questions which I couldn't find documentation on -

1. Can I change the permlinks?
2. Do we have Categories like we have Tags?
3. Is there a pagination plugin/feature?

Thanks.

**Comment by manikmagar** [comment]
1. Can I change the permlinks? - See something for extensionless uri's in master. I will be checking it out soon.
2. Do we have Categories like we have Tags? - Will be adding categories support in my forked out jbake soon.
3. Is there a pagination plugin/feature? - I see the code is being implemented in `master` for this. Hope to get it in v2.5.0 but in mean time I might give a shot to snapshot version.

Thanks!

**Comment by jonbullock** [comment]
Hi Manik

1. The permlink is directly driven by the filename of the source file. As you highlight the extension is optional or will be soon.
2. Thanks I'll review once I've got 2.5.0 released.
3. Yeah paging has been added for the index page only at the moment.

**Comment by manikmagar** [comment]
Hi @Jonathon,

Thanks for checking out. I have two sites Manik.magar.me and UnitTesters.com that are baked with JBake. 

For unittesters.com I am using my forked version of JBake where I have merged my two PRs #293 and #294 that I Implemented for permalink customization and categories ( you can see them I use at UnitTesters.com)

These PRs are on source repo too.

Again, thanks for all the effort on JBake.
