### ISSUE TITLE
@JavaBake vs @JBakeOrg - Twitter Handle

### ISSUE THREAD

**Issue by manikmagar** [jbake-org/jbake#287]
While twitting about JBake, I was searching for JBake handle with some natural choice of something starting with JBake. I think Jbake is not available but how about @JBakeOrg, easy to find and know .... it may be just me :)

**Comment by manikmagar** [comment]
I think it should be on jbake-org repo :)

**Comment by jonbullock** [comment]
Yeah unfortunately @jbake was taken on Twitter and on here. I have acquired javabake on here as well just in case, and I probably prefer that to jbake-org but at the time I moved the repo I went with what matched the domain name. On Twitter I tend to use the hashtag #jbake
