### ISSUE TITLE
2.4.1 Release

### ISSUE THREAD

**Issue by jaguililla** [jbake-org/jbake#289]
It would be great if you could release the development version as it is with 2.4.1?

This would fix some issues until the next stable version. Ie: problems with Gradle daemon.

Would this be possible?

**Comment by manikmagar** [comment]
👍  Vote +1

**Comment by volyx** [comment]
+1

**Comment by jonbullock** [comment]
All the scheduled issues for v2.5.0 are now complete, so not long now until the next release.

**Comment by jaguililla** [comment]
That's great! thank you very much
