### ISSUE TITLE
Blog posts get duplicated when `db.store=local` is used

### ISSUE THREAD

**Issue by jjkavalam** [jbake-org/jbake#290]
Partial rendering is a great addition to jbake and potentially very useful !  However, with v2.4.0, I am having trouble when using `db.store=local`

**Problem:** Blog posts get duplicated when `db.store=local` is used

**How to reproduce?:** Take the `example_project_freemarker` that comes bundled with `jbake-2.4.0-bin.zip` release and edit `jbake.properties` by adding  `db.store=local`. Then  run `..\bin\jbake` from the project folder to generate the output.

Each time the command is run, the blog posts get duplicated. That is after `n` runs I have `n` copies of each post (see the screenshot of the `index.html` page after I baked 3 times: 
[screencapture-example_project_freemarker-output-index-html.png](https://drive.google.com/open?id=0Bxqosq_iA6nSZkdhYUlFWDlWMkE))

**Comment by dinesh19aug** [comment]
If you are using db.store=local then you need to pass --reset option. So in your case 
the command should be bake -b -s --reset.

**Comment by dinesh19aug** [comment]
Actually it is a bug and I was just going through the code and see this.
In the project example_project_freemarker folder under output/cache where posts.ocl is saved, The sha1 key is changing as result an existing files is marked as new and is displayed twice. 

The code is in Crawler class
 private DocumentStatus findDocumentStatus(String docType, String uri, String sha1) {
        List<ODocument> match = db.getDocumentStatus(docType, uri);
        if (!match.isEmpty()) {
            ODocument entries = match.get(0);
            String oldHash = entries.field(String.valueOf(DocumentAttributes.SHA1));
            if (!(oldHash.equals(sha1)) || Boolean.FALSE.equals(entries.field(String.valueOf(DocumentAttributes.RENDERED)))) {
                return DocumentStatus.UPDATED;
            } else {
                return DocumentStatus.IDENTICAL;
            }
        } else {
            return DocumentStatus.NEW;
        }
    }

**Comment by obfischer** [comment]
+1

**Comment by jonbullock** [comment]
This bug has been fixed in v2.5.0 as part of #226.
