### ISSUE TITLE
startup script does not resolve symlinks

### ISSUE THREAD

**Issue by raupachz** [jbake-org/jbake#297]
The startup bash script does not resolve symlinks. How to reproduce from any directory:

```
$ ln -s $JBAKE_HOME/bin/jbake jbake
$ ./jbake
Error: Unable to access jarfile ./jbake-core.jar
```

 This is a bit problematic if you want to install jbake in a more linux/unix way.

**Comment by jonbullock** [comment]
Thanks for raising this issue, there are a number of improvements I'm looking to make to the startup scripts as they were quickly created when I first released the code but not been looked at since.

**Comment by jonbullock** [comment]
Relates to #230 #182

**Comment by ancho** [comment]
Maybe the scripts generated by the gradle application plugin solve that problem. See #280.

**Comment by jonbullock** [comment]
Definitely looks like an option. 👍

**Comment by jonbullock** [comment]
Need to check if this is still an issue after switch to Gradle.

**Comment by jonbullock** [comment]
Checked scenario again and startup script resolves symlinks now we've switched to Gradle.
