### ISSUE TITLE
Improve Pagination support so next/previous filenames can be customised to the point that it allows URL's such as /blog/1 /blog/2

### ISSUE THREAD

**Issue by SergeyPirogov** [jbake-org/jbake#308]
Hi,

I started to move my blog from ghost to Jbake and found that now it's not possible to add page paggination.

Now we can set post per page, but how to switch between pages?

**Comment by jonbullock** [comment]
In 2.5.0 pagination support has been added to the special index page. You can add links to switch between pages in your template engine by using the additional data variables explained in the docs: http://jbake.org/docs/2.5.0/#index

**Comment by SergeyPirogov** [comment]
Thanks, I think it would be better to not paginate like index2.html, index3.html, but instead we can do folders like 2, 3, 4 with corresponding index.html files inside, so it wil be possible to use url as http:://host:post:/blog/2/

**Comment by jonbullock** [comment]
Unfortunately that's not possible at the moment with JBake, the page filenames is pretty baked into the code at the moment. We do support extensionless URI's but this doesn't extend to the special pages at the moment either. Both of these aspects can be changed in a subsequent release though.

Thanks for taking the time to raise this issue though. 👍

**Comment by SergeyPirogov** [comment]
Actually now I want to add paging and do it as:

```
<#if (nextFileName)??>
    	        <a class="pagination-item pagination-next" href="${nextFileName}"><i class="icon-arrow-left"></i> <span>Newer Posts</span></a>
    	    </#if>
    	    <span class="pagination-info">Page {{page}} of {{pages}}</span>
    	    <#if (previousFileName)??>
    	        <a class="pagination-item pagination-prev" href="${previousFileName}"><span>Older Posts</span> <i class="icon-arrow-right"></i></a>
    	    </#if>
```

But it says that this variable is ubdefined. So I don't have paging buttons.

I have 2 pages with 5 articles for each

**Comment by jonbullock** [comment]
Looks like @ancho has already implemented the enhancement you outlined.

I've just checked the code & docs again on paging and you need to define the following options in your jbake.properties for those paging variables to be made available

````
index.paginate=true
index.posts_per_page=5
````

Have you defined these?

**Comment by SergeyPirogov** [comment]
Yes, I did everything the same

**Comment by jonbullock** [comment]
OK thanks just wanted to double check.
