### ISSUE TITLE
JBake JettyServer doesn't work with custom destination

### ISSUE THREAD

**Issue by jmcgarr** [jbake-org/jbake#314]
I am running a JBake site using the Gradle plugin. I am partial (and so it the plugin) to using the `src/jbake` directory for source and the `build/jbake` directory for output. I cannot get jbake to serve content using these two directories. Here's the command I used:

`jbake src/jbake build/jbake -b -s`

This results in a successful bake to the `build/jbake` directory, but the Jetty server presents content from the `output` directory. 

Planning on trying to create a unit test to replicate this.

**Comment by jonbullock** [comment]
At first glance this is probably down to the fact that the -s option is configured to use the source parameter.

**Comment by ancho** [comment]
It is also possible to apply the gradle gretty plugin. For example:

```
plugins {
     id 'org.akhikhl.gretty' version '1.4.0'
}

 gretty {
     httpPort = 8881
     contextPath = "/blog/"
     extraResourceBases = ["build/jbake"]
 }
```

Run `gradle jettyRun` to fire up jetty with your fresh baked website.

See https://github.com/ancho/calmdev-website for a configuration with different target environments (local, test and prod).

**Comment by jmcgarr** [comment]
Thanks for that @ancho. 

I really wanted the `jbake-gradle-plugin` to take advantage of the new file watching features built into the `Main.java`. My hope is to land this fix so I can push that PR as well.

**Comment by ancho** [comment]
gradle has a continuous build feature `gradle -t`. It watches for changes of the task inputs an runs the task again if something has changed.

See https://www.calmdevelopment.de/blog/2016/08/jbake-continuous-with-gradle.html

**Comment by ancho** [comment]
But don't get me wrong. It's still a bug and need to be fixed. Thank you for cleaning up and improving the application.

**Comment by jonbullock** [comment]
See #316
