### ISSUE TITLE
Expand allowed characters for template type name

### ISSUE THREAD

**Issue by beikov** [jbake-org/jbake#317]
As discussed on the mailing list, please allow for other characters in the template type name.

> So I was trying to define a template type and it didn't produce output when the name contained characters like '_' or '-'.
> Is there a set of characters that are allowed? Can these maybe be extended to also include at least '_'?

**Comment by jonbullock** [comment]
Need to allow dash and underscore characters and also include details of limitation in documentation.

**Comment by ancho** [comment]
Maybe this one is a candidate for 2.6.0?
