### ISSUE TITLE
update orientdb

### ISSUE THREAD

**Issue by ancho** [jbake-org/jbake#318]
A user at the mailing list was confused about the warning "Current implementation of storage does not support sbtree collections" . See https://groups.google.com/forum/#!topic/jbake-user/8hdkh-zl_Sk

It has maybe something to do with indexes and the currently used version of orientdb (1.7.10).

The current version of orientdb is 2.2.12

**Comment by jonbullock** [comment]
Yeah I want to work out what's caused that warning, I remember trying to upgrade the version but the structure has changed from 1.x to 2.x so it wasn't quite as easy as updating the version in the POM file.
