### ISSUE TITLE
Add support for YAML formatted config file

### ISSUE THREAD

**Issue by jonbullock** [jbake-org/jbake#32]
So more complex data structures can be used.

No specific use cases as yet, will be done once requirement exists.

Research:

http://www.yaml.org/
http://stackoverflow.com/questions/450399/which-java-yaml-library-should-i-use
https://code.google.com/p/snakeyaml/

**Comment by wadechandler** [comment]
I would really like to support "side car" files for not just config, but for meta-data. I think that would make the content cleaner, and keep out foreign syntax. I will create a separate issue for that.

**Comment by LightGuard** [comment]
Doesn't groovy support reading YAML out of the box? If so, we wouldn't need to add any dependencies and it should be a simple fix to add it to the list of support config parsers.

**Comment by jonbullock** [comment]
It does but Groovy is an [optional](https://github.com/jbake-org/jbake/blob/master/jbake-core/build.gradle#L20-L22) dependency at present and we only include the modules needed for it's template engines. Adding the YAML dependency is not a problem though. However, I assume this is in relation to #680, if so I'd prefer to keep content for output separate from the config.

**Comment by ge0ffrey** [comment]
An illustration on how it works in Awestruct (= dead project that we want to replace by JBake or Jekyll), which I created for the other image:
![image](https://user-images.githubusercontent.com/176880/116198955-e2cb9f00-a736-11eb-829a-433d47c89484.png)
