### ISSUE TITLE
Allow certain folders to be ignored from being processed either as content or assets

### ISSUE THREAD

**Issue by jonbullock** [jbake-org/jbake#324]
Allow certain folders to be ignored from being processed either as content or assets.

**Comment by jonbullock** [comment]
See #281 and related issue #321

**Comment by manikmagar** [comment]
I think we can ignore the folders or files starting with '.'

In addition to that, will there be a need to ignore a folder if it contains `.jbakeignore` file?

For #281, any files/folders in content directory that are not ignored by above rule and file extension is not registered with [Markup engine](https://github.com/jbake-org/jbake/blob/master/src/main/resources/META-INF/org.jbake.parser.MarkupEngines.properties) can possibly be copied to output folder.

**Comment by jonbullock** [comment]
All sounds good to me 👍

**Comment by manikmagar** [comment]
I was trying this and it seems creating a file or folder starting with . has restrictions (at least in mac) i.e. they may not be too user friendly to create. Should we instead use '_' i.e. ignore files starting with _ in name or folder containing _jbakeignore should be ignored including its children?

@jonbullock @ancho any thoughts?

**Comment by ancho** [comment]
I'm with `.jbakeignore`. People using git should be used to it. What's your problem creating a hidden file with mac? Doesn't a `touch .jbakeignore` work?
With Windows there should be the trick with creating a file like `.jbakeignore.` which should create a file without an extension.

**Comment by manikmagar** [comment]
Creating with terminal works but was thinking for users working in finder or other tools. But I think you are right, staying with .jbakeignore is good and similar to other standard implementations like .gitignore, .svn etc. 👍
