### ISSUE TITLE
Index template is not rendered regardless of config if no content of type post exists in site/project

### ISSUE THREAD

**Issue by jonbullock** [jbake-org/jbake#325]
Index template is not rendered regardless of config if no content of type post exists in site/project.

**Comment by ancho** [comment]
Hmm. Should already be fixed with #312.

**Comment by jonbullock** [comment]
Yeah just after I committed a fix I started to look at merging #312 in and
noticed you had fixed it as well. I've reverted my fix now and will merge
#312 in.

On 22 Dec 2016 12:32 am, "Frank Becker" <notifications@github.com> wrote:

Hmm. Should already be fixed with #312
<https://github.com/jbake-org/jbake/pull/312>.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/jbake-org/jbake/issues/325#issuecomment-268686128>, or mute
the thread

**Comment by ancho** [comment]
You answered to a previous message. I reviewed your change and I was wrong. There needs to be a fallback for paginated index rendering in case there is no post available. 
Added a test and pushed a commit to #312.
