### ISSUE TITLE
Ability to add github styled internal links to markdown

### ISSUE THREAD

**Issue by lidderupk** [jbake-org/jbake#335]
Wondering if jbake supports inline anchor tags. For example if the markdown looked like

#Introduction
Sample text.

Then the following would link to "Introduction" above.

```- [Introduction](#introduction)```

Github generates the following code to the heading that makes it linkable. 

```<a href="#introduction">Introduction</a>```

I understand that the markdown may be generated by a different library that we are not able to change. In general, if I want to add something to jbake, what is the best way to extend without changing the core source? Please advise.

**Comment by jonbullock** [comment]
JBake is using [Pegdown](https://github.com/sirthias/pegdown#introduction) for Markdown support and it does have an extension for ANCHORLINKS so you can enable this by altering your ```jbake.properties``` - see this section of the [docs](http://jbake.org/docs/2.5.0/#markdown_extensions) for more info
