### ISSUE TITLE
preview fails if bake was not called before

### ISSUE THREAD

**Issue by xamde** [jbake-org/jbake#343]
The doc http://jbake.org/docs/2.5.1/#preview says, "jbake -s" will show the output. However, it failed if "jbake  -b" was not called before.

**Comment by shalugin** [comment]
@xamde I think that the key in phrase: "You can then see what your **baked project** looks like immediately by running JBake"

**Comment by xamde** [comment]
I expected the "watch source folder" feature to take care of this. But I found the watch folder feature not to work as expected (seems to work only if content is changed, not if templates are changed). Nevertheless, I agree, I mis-read the docs, this issue can be closed.

**Comment by jonbullock** [comment]
@xamde could you open an issue to extend the watch mode to include the template folder as well?
