### ISSUE TITLE
Archive Formatting with New Installation of Jbake + Jade is Broken 

### ISSUE THREAD

**Issue by levlaz** [jbake-org/jbake#345]
On a fresh install of Jbake using the [jade4j](https://github.com/neuland/jade4j) templating language, when you visit the archive page it does not appear to properly format the date, and some of the jade syntax appears in the html. (as shown in the screenshot) 

![screen shot 2017-04-08 at 12 58 18 pm](https://cloud.githubusercontent.com/assets/7981032/24832011/602f579a-1c5b-11e7-8776-67f0b3b805c2.png)

I am running JBake v2.5.1 on MacOS Sierra installed via homebrew. 

### Steps to Reproduce 

```
mkdir test 
cd test 
jbake -i -t jade
jbake -b
jbake -s
```

Navigate to [http://localhost:8820/archive.html](http://localhost:8820/archive.html)

The offending default template looks like this: 

```
doctype html
html
  include header.jade
  body(onload="prettyPrint()")
    div#wrap
      include menu.jade
      div.container

        div.page-header
          h1 Blog Archive

          each post in posts
            if formatter.format(post.date,"MMMM yyyy") != last_month
              h3 #{formatter.format(post.date,"MMMM yyyy")}

            h4 #{formatter.format(post.date,"dd")} -
              a(href='#{post.uri}') #{post.title}

            last_month = formatter.format(post.date,"MMMM yyyy")

  include footer.jade
```

I am not 100% sure what the purpose of `last_month` is here in this context.

**Comment by jonbullock** [comment]
Thanks for raising this issue, I'm able to replicate it.

**Comment by jonbullock** [comment]
It's to limit the output of the month & year so it's not output for each post. The line should be:

````
- var last_month = formatter.format(post.date,"MMMM yyyy")
````
I'll make sure this is fixed in the default template files.
