### ISSUE TITLE
Make tagged documents data available as global data.

### ISSUE THREAD

**Issue by manikmagar** [jbake-org/jbake#350]
As of now, only `alltags` is available globally and it only contains String list of tag names. For one of the blogs, on home page, I want to show  number of documents in each tag, which doesn't seem possible or easily achievable.  May be alltags can return list of Tag model where Tag object could be a map of `{ "name" : "test", "noOfDocuments": 30, page-url: "{name/sanitizedname}"}` or more elements.

I can write a script in template to iterate over `published_posts` or `published_content` and then get the stats but that will slow down rendering along with adding other scripting complexities to templates.

P.S. I actually wanted to show categories and their post count but until #293 is available in release, I am choosing tags. Although, even categories then should be made available globally with more data elements.

**Comment by manikmagar** [comment]
For the number of tagged posts, this one seems to be duplicate of #216 .

**Comment by manikmagar** [comment]
Accidentally closed it while adding previous comment, I will keep it open for review to see if more data about tags should be exposed? I am going to use the solution specified in #216 .

**Comment by ancho** [comment]
Jup. That would be nice. I think a refactoring to a better data model abstraction is the right way to go.
