### ISSUE TITLE
Add rendering support to generate /tags homepage

### ISSUE THREAD

**Issue by manikmagar** [jbake-org/jbake#351]
Individual tags are rendered inside /tags or ${config.tags_path} folder but there is no way to define template page for /tags itself. As of now, if /tags is hit and if directory listing is enabled, then it just displays directory listing of tag html files. Instead of that, a new template should be added to allow rendering for /tags home page. This is helpful when you just want to add site menu 'Tags' which lands to all tags home page.  
eg.
`template.tag.home.file=tagshome.ftl`

For example, categories implemented in #293 .

Thanks.

**Comment by manikmagar** [comment]
This is part of #165

**Comment by jonbullock** [comment]
Great suggestion, thanks for raising this.

**Comment by manikmagar** [comment]
@jonbullock Have you already started working on this? If not, I can add this one.

**Comment by jonbullock** [comment]
No I haven't, if you want to take this on that would be great.

**Comment by manikmagar** [comment]
Sure, will send PR soon. Dev is almost done, need to add test cases.
