### ISSUE TITLE
Relative path's are broken due to wrong rootpath when extensionless uri is enabled.

### ISSUE THREAD

**Issue by manikmagar** [jbake-org/jbake#360]
When extensionless uri's are enabled. [Crawler](https://github.com/jbake-org/jbake/blob/master/src/main/java/org/jbake/app/Crawler.java) is making rootpath first but not updating it with one more '../' when extension less uri is on.

**Comment by jonbullock** [comment]
Thanks for catching this one.

**Comment by manikmagar** [comment]
Working on a fix, will send PR soon.

**Comment by manikmagar** [comment]
I found same issue for paginated index pages also. eg. blog/2/index.html was missing one level "../" in rootpath. PR fixes both issues.

**Comment by jonbullock** [comment]
👍

**Comment by manikmagar** [comment]
Do you have a date in mind for 2.6? I feel the bug fixes should be released sooner than enhancements. May be 2.5.2!

**Comment by jonbullock** [comment]
The date I originally had in mind has come and gone, so it's ASAP at the moment. I'll review what's left to do for 2.6.0 and if it's a while off I'll look at pushing out a bug fix release.

**Comment by manikmagar** [comment]
This bug has left the extensionless uri and pagination not usable as all static asset references using relative paths will break causing sites not to render properly. 

**Workaround in meantime:**
For sites rendered at root, absolute paths can be use eg. /css/main.css instead of relative like ../css/main.css.
For subfolder sites, add folder name /blog/css/main.css

**Comment by benelog** [comment]
I am waiting release of 2.6.0 for a month.
If the 2.6.0 release takes time, it may be better to release 2.5.2 to fix this issue.
