### ISSUE TITLE
Generate 404 page not found html

### ISSUE THREAD

**Issue by manikmagar** [jbake-org/jbake#365]
No matter where static website/blog is hosted, you would always want a page to display when 404 page not found error occurs. 

Github pages may be the most popular ( & free :) ) place to host static sites. Github does support adding a custom 404 page not found file in github-pages - See [this](https://help.github.com/articles/creating-a-custom-404-page-for-your-github-pages-site/). It is simple, 404.html should exist at the root of your gh-pages.

There are few ways to do this with -

1. Add a content page at the root of content folder and let it render with page template. Example [here](https://github.com/manikmagar/jbake-future-imperfect-template/blob/master/content/404.html). 
2. Register a new custom type 404, create a template file for the custom type and add a content 404 file. This will render 404.html with the dedicated template for 404.
3. Add a support in JBake to by default generate a 404.html file at the root. Templates can have a 404.ftl (or similar template) which is rendered by JBake. No need to add any content. 

I feel JBake should by default generate 404 (option 3), that way it feels to be part of framework.

Any thoughts?

**Comment by jonbullock** [comment]
My initial thought is that option 2 exists to deal with this type of scenario. Long term I'm thinking this could be dealt with by a specific plugin/extension, to create pages like this.

But I'm eager to hear others opinion on this...

**Comment by manikmagar** [comment]
In my opinion, 404 should be treated as a content-independent basic component of a site similar to sitemap, rss which are generated by JBake. I know they show content list but we don't have to register them as a type or add sitemap as a content, framework generates it.

Registering custom components is definitely useful and required to define user-defined content types.

**Comment by jonbullock** [comment]
I've been thinking about this some more and I've changed my view, this should be handled by JBake, so option 3.

**Comment by ottlinger** [comment]
+1 for option 3
