### ISSUE TITLE
consider using editorconfig to maintain a common coding style

### ISSUE THREAD

**Issue by ancho** [jbake-org/jbake#372]
The current code base is a mixture of different format styles caused by different IDE settings (and personal comfort). 
Maybe we can use http://editorconfig.org/ to define a set of basic styles (Tabs vs. spaces, Indentation, windows vs. *nix newlines. ) for different file formats. There are [plugins](http://editorconfig.org/#download) for a bunch of IDE's and text editors available.

**Comment by ottlinger** [comment]
I do like the idea and would even favour a plugin that applies change upon checkin such as
https://github.com/revelc/formatter-maven-plugin

But an editorconfig is a first step towards that direction :+1:

**Comment by jonbullock** [comment]
Definitely agree... this is something that's been mentioned in other issues before. The sticking point has been outstanding PR's previously, the number did get down quite low recently but you guys keep working hard and creating more ;-)

I don't know whether it's possible but I did think of stopping PR's from being raised for a period of time while the outstanding PR's are merged and this can be applied... what do you think? Happy to hear of any other ways to achieve this?

**Comment by wadechandler** [comment]
Some things that editorconfig has yet to address however are things like what to do with newlines after curly braces `{` and offsets within context such as many IDEs and editors provide for C like languages etc. I think it is good, but I have hoped the editorconfig specification would move faster on these type issues.

**Comment by ancho** [comment]
Ok. It was only a quick idea. The easiest possible solution. As an addition we maybe could make use of [checkstyle](https://docs.gradle.org/3.5/userguide/checkstyle_plugin.html).

**Comment by OndraZizka** [comment]
One of the approaches is to define an Eclipse formatter settings, export that file, and then use this IDEA plugin: https://plugins.jetbrains.com/plugin/6546-eclipse-code-formatter
There's also NetBeans plugin somewhere.

That, of course, won't cover if someone is coding in something else. Is that the case?

**Comment by ancho** [comment]
hmm...ok. that's the reason I mentioned checkstyle which is supported by a bunch of IDEs and build tools.
I could create a sample configuration and we see what it feels like?
There are two [style configurations](https://checkstyle.org/style_configs.html) we could choose one and customize them to our needs. What do you think?

@jonbullock I'm not quite sure if we really should freeze PR's. Maybe merge the bigger ones. clean up the whole projekt and deal with the smaller ones later?

**Comment by jonbullock** [comment]
@ancho Experience suggests more will be created while merging them in but we can't do nothing so lets go for it.

I did put a section in the contributors guide to try and avoid this scenario by asking for new features to be proposed on the mailing list first before the PR is created but that just hasn't happened so far... so I'll look at different approaches

**Comment by lefou** [comment]
> Some things that editorconfig has yet to address however are things like what to do with newlines after curly braces { and offsets within context such as many IDEs and editors provide for C like languages etc.

Editorconfig is not a general purpose formatter, but help to avoid unwanted whole-file changes, by defining some defaults for settings that are normally platform- and culture-specific.
