### ISSUE TITLE
Support german umlauts in jbake.properties

### ISSUE THREAD

**Issue by GeorgHenkel** [jbake-org/jbake#392]
Hi,
I am using current version 2.5.1 of JBake and have the problem, that german umlauts in the `jbake.properties` do not get encoded correctly, as it seems. 

In the `jbake.properties` I use the following as menu headline:

    site.menus.main.about.label=Über uns

but the ouput in the menu bar is: 

![image](https://user-images.githubusercontent.com/1669956/27945030-e389dd38-62ea-11e7-864c-274c88a37444.png)

The encoding of the `jbake.properties` and the `menu.ftl` is UTF-8 without BOM. And charset for the webpage is `<meta charset="utf-8"/>`.

**Comment by GeorgHenkel** [comment]
I have found a workaround for this. 
Using unicode instead of umlauts will work.

**Comment by SiddheshRane** [comment]
This is actually related to property files in Java, nothing particular to JBake as such. I had ran into a similar problem when I was creating translated resource bundles, which are just property files, for a Java app. You have to use unicode escape sequences to have non ascii text.

For editing convenience open the jbake.properties file in an IDE like NetBeans or Eclipse and use its graphical key value interface. You can write naturally in umlauts and the IDE will convert them to escape sequences for you.

**Comment by mikolak-net** [comment]
@SiddheshRane is unfortunately right. For reference, [here's how](https://www.jetbrains.com/help/idea/configuring-encoding-for-properties-files.html) to set up transparent edition in InelliJ IDEA (just had to fish this out, it's pretty obscure otherwise).

**Comment by oliverlietz** [comment]
> In Java SE 9, properties files are loaded in UTF-8 encoding.

see https://docs.oracle.com/javase/9/intl/internationalization-enhancements-jdk-9.htm#JSINT-GUID-974CF488-23E8-4963-A322-82006A7A14C7

**Comment by mikolak-net** [comment]
Well, that pretty much renders my question moot then in this context.
