### ISSUE TITLE
Parsing included asciidoctor files for header

### ISSUE THREAD

**Issue by danielkocot** [jbake-org/jbake#416]
When baking the site with documents which that are included in an other asciidoctor file. I get this error message from jbake.

Error parsing meta data from header (missing type or status value) for file file.ad!
file.ad has an invalid header, it has been ignored!

Anyone who knows a workaround for that?

**Comment by manikmagar** [comment]
@danielkocot  status, type and date are required header tags for every file. Here is an example from JBake docs, this index file includes other file. 

https://github.com/jbake-org/jbake.org/blob/master/content/docs/2.6.0/index.ad

Checkout the installation.ad file for the minimal headers included. Can you compare that and see if what you are missing?

**Comment by danielkocot** [comment]
@manikmagar I looked at it. And it doesn't feel right to include a certain document by a range of lines. It should be possible to use the standard include from Asciidoctor and just bake the index document.

**Comment by jonbullock** [comment]
A feature in 2.6.0 should help this and remove those warnings from the include files being processed. If you place your includes in a sub folder you can then mark the folder as being [ignored](https://jbake.org/docs/2.6.0/#ignoring_files_and_directories) so JBake doesn't try and process them. I am assuming that you don't want the included files to be rendered individually.
