### ISSUE TITLE
Handle included ad files as includes not as separate HTML files

### ISSUE THREAD

**Issue by danielkocot** [jbake-org/jbake#423]
Actually an included ascidoctor file is not really handled as included file. Using a separate HTML file will be created and content is not placed directly within the origin file.
If anybody does this now, JBake responses with an parsing meta data error.

**Comment by jonbullock** [comment]
I'm assuming this relates to #416, the [ignore](https://jbake.org/docs/2.6.0/#ignoring_files_and_directories) option will allow the included AsciiDoc files to be just treated as includes by Asciidoctor and not processed as content as well by JBake.

Let me know if my assumption is wrong though :)

**Comment by danielkocot** [comment]
Hi @jonbullock, your assumption is correct. I will check this out. Thanks for the hint. There wasn't enough time to have a closer look at the new release because I was on sick leave for the last two weeks.

**Comment by jonbullock** [comment]
No worries, I'll close this issue.
