### ISSUE TITLE
Option to generate relative image links in output

### ISSUE THREAD

**Issue by msgilligan** [jbake-org/jbake#440]
I want to generate an output site file tree that has _relative_ links to the images. I don't want to use server mode -- I want an _accurate_ preview loading from `file://` URLs. I also want the option to post to a staging and production server (using Gitlab CI) so the image links shouldn't be hardcoded to the production server.

But the images are pulled from the previously published version of the site running on `site.host`.

According to the documentation `site.host` should contain the URL of the server and is overridden for server mode. But there appears to be no (easy) way to request the generation of relative image links in the output.

I'm in the process of updating to JBake 2.6.0.

Note https://github.com/jbake-org/jbake-gradle-plugin/issues/32 -- Gradle plugin doesn't support server mode.

**Comment by manikmagar** [comment]
Thanks for raising this issue.

With 2.6.0, the image URL generation has changed (you may have already seen [this](https://jbake.org/docs/2.6.0/#images_path)). This change skips the images where URL explicitly starts with http:// or https://. I think the initial version of change also excluded modifying image URLs starting with `/`. I wonder if that would have helped to achieve this setup.

Were you able to achieve all this with 2.5.1 where image path's are not modified? 

Running in server mode could be used while testing site in local.

**Comment by msgilligan** [comment]
> I think the initial version of change also excluded modifying image URLs starting with / . I wonder if that would have helped to achieve this setup.

I don't think that will help. For example if the file is in `/blog/2018` -- and what happens when you want to preview from a `file://` URL from some subdir of your home directory.

> Were you able to achieve all this with 2.5.1 where image path's are not modified?

I don't remember what was happening with 2.5.1 (I either wasn't having a problem or links were to existing images that were already on the `http://` links on the server). I upgraded to 2.6.0 to get a few of the new features.

>Running in server mode could be used while testing site in local.

Gradle plugin doesn't support server mode: https://github.com/jbake-org/jbake-gradle-plugin/issues/32

**Comment by msgilligan** [comment]
Thanks @ancho, I may try that.

**Comment by msgilligan** [comment]
How hard would this be to fix? Is it something that could be easily submitted as a PR?

**Comment by msgilligan** [comment]
@jonbullock It seems to me a static site generator should be able to generate fully static sites that:

1. Are entirely self-contained
2. Can be  opened and navigated by opening `index.html` in any root directory on the file system
3. Can be deployed to multiple servers on multiple URLs without any modification.

Any suggestions on what we can do got get his fixed? I'm willing to help if given some guidance and this is not too difficult.
