### ISSUE TITLE
Upgrade to AsciidoctorJ 1.5.7 (so JRuby dependency is also updated to enable use with Java 9)

### ISSUE THREAD

**Issue by beikov** [jbake-org/jbake#462]
After using the following dependency, the usage with Java 9 started working for me.

```
<dependency>
	<groupId>org.jruby</groupId>
	<artifactId>jruby-complete</artifactId>
	<version>9.1.15.0</version>
</dependency>
```

Maybe you could update the dependency version that come transitively from the asciidoctorj dependency to allow using Java 9.

**Comment by ancho** [comment]
Thanks for reporting this and showing a solution.
asciidoctorj 1.5.7 will switch to jruby [9.1.16.0](https://github.com/asciidoctor/asciidoctorj/blob/master/build.gradle#L41). As soon as the release is out, we will switch to that version.
I like that better as to overwrite a dependency that is yet not supported upstream.

**Comment by ancho** [comment]
#603 contains an update to asciidoctorj 2.2.0. should fix the problem.
