### ISSUE TITLE
asciidoc does not render property from jbake.properties / how to insert user-defined properties into ASCII-Doc-Files' code blocks

### ISSUE THREAD

**Issue by ottlinger** [jbake-org/jbake#467]
Apache's incubating project Tamaya uses JBake to produce its webpage - thanks for the work!

We are running on 2.6.1 and defined a property in [jbake.properties](https://github.com/apache/incubator-tamaya-site/blob/master/jbake.properties).
This property value can be referenced in ´-sections of ADOC-files, but is not visible within source blocks. Its value is not generated as can be seen here:
https://tamaya.incubator.apache.org/documentation/extensions/mod_collections.html
with tamaya_version - see source [adoc file](https://github.com/apache/incubator-tamaya-site/blob/master/content/documentation/extensions/mod_collections.adoc)

# Not working

```
[source, xml]
-----------------------------------------------
<dependency>
  <groupId>org.apache.tamaya.ext</groupId>
  <artifactId>tamaya-collections</artifactId>
  <version>{tamaya_version}</version>
</dependency>
-----------------------------------------------
```

# Working
`1. Add BACKTICK{tamaya_mvn_group_id}:tamaya-core:{tamaya_version}BACKTICK to your dependencies.`

A different page is able to render to property value, but only within a source include:
https://tamaya.incubator.apache.org/start.html
https://raw.githubusercontent.com/apache/incubator-tamaya-site/master/content/start.adoc
(see placeholder usage tamaya_version)

Is this a problem within jbake's asciidoc-parser or how can I transfer defined property values into source blocks?

Thanks

**Comment by ancho** [comment]
Hi,

set `asciidoctor.attributes.export` to true. If you want a prefix for jbake properties you can set `asciidoctor.attributes.export.prefix`.

Say you have a property `tamaya.version` and `asciidoctor.attributes.export.prefix=jbake-` and `asciidoctor.attributes.export=true` the asciidoctor attribute will be referenced as `{jbake-tamaya_version}`

The defaults are:

`asciidoctor.attributes.export=false`
`asciidoctor.attributes.export.prefix=`

So unfortunately the feature is disabled per default -.-

**Comment by ottlinger** [comment]
Thanks, is there a reason to disable the feature by default?

Maybe I didn't find the correct part in the docs about that property before ...
will try out and give feedback.

**Comment by ancho** [comment]
I don't think so. But I'm not quite sure. Maybe @jonbullock knows the reason behind the decision.

Here is the [link to the documentation](https://jbake.org/docs/2.6.1/#export_jbake_configuration_to_asciidoctor_content)

**Comment by jonbullock** [comment]
From recollection I don't think there was an explicit reason to disable it, however I can imagine this was disabled due to the impact it may have, it could overwrite attributes set in the source AsciiDoc files. Although I could be wrong here, and if I am then I can't think of any other reason why it couldn't be enabled by default in a future release.

**Comment by ancho** [comment]
Yes. That sounds logical. For example the version property collides with the assciidoctor version attribute. That's the reason for the prefix which should be set to "jbake-" if export is enabled per default or something like that.

**Comment by jonbullock** [comment]
Yeah sounds reasonable, I'll create an issue to have to enabled by default along with a "jbake-" prefix.

**Comment by ottlinger** [comment]
Thanks.

**Comment by ottlinger** [comment]
@ancho do you have a working example - I tried to integrate your proposed changes but no value is introduced in the code block of the page - any hints?

**Comment by ancho** [comment]
Given in jbake.properties:

```
asciidoctor.attributes.export = true
asciidoctor.attributes.export.prefix = "jbake-"
tamara_version = "0.0.1"
```

You can access the attribute in your adoc file like:

```
tamara-version: {jbake-tamara_version}

[source,sub="attributes"]
----
tamara-version: {jbake-tamara_version}
----

See https://asciidoctor.org/docs/user-manual/#attributes for more information about using attributes with asciidoctor.

**Comment by ottlinger** [comment]
@ancho thanks for the info - trying to integrate it into Tamaya does not work properly. Can you spot my mistake?

* https://github.com/apache/incubator-tamaya-site/blob/master/jbake.properties
* https://github.com/apache/incubator-tamaya-site/blob/master/content/documentation/extensions/mod_camel.adoc
contains property references in source elements and normal text.
Both do not show up properly:
https://tamaya.incubator.apache.org/documentation/extensions/mod_camel.html

(I'll be offline the next week, so don't worry about a delayed answer from me)

**Comment by ancho** [comment]
Hi @ottlinger ,

you have an error in your jbake.properties file.

asciidoctor.attributes.prefix != asciidoctor.attributes.export.prefix

See https://github.com/apache/incubator-tamaya-site/blob/a1aaef03059dd2e31e1c531de0658bcb35b53280/jbake.properties#L18

Hope you had a nice offline week, assuming you are reading it after your week off ;)

**Comment by jonbullock** [comment]
Can this be closed now?

**Comment by ottlinger** [comment]
@jonbullock not sure if there was an issue that updated the documentation about the default behaviour?

**Comment by jonbullock** [comment]
Just double checked and the docs do state what the current default is: https://jbake.org/docs/2.6.3/#export_jbake_configuration_to_asciidoctor_content

And there is an issue to change the default behaviour in a future release.
