### ISSUE TITLE
Alternative header separator - ~~~~~ is treated as start of code by some Markdown flavors

### ISSUE THREAD

**Issue by OndraZizka** [jbake-org/jbake#475]
Edit: Duplicates #231 and #419 

Currently, ~~~~~ is used to separate the document header from the content.

Many Markdown renderers, including GitHub's (try it), and IDEA's Markdown plugin, is handled as a start of a code block.

That leads to  
 * the document source is improperly syntax-highlighted,
 * the preview is all code from the header to the end of the page.

I suggest to introduce a different header syntax, so that the rest of the page renders properly.

The ideal would be to make it compatible with Markdown, so that
 * the header would appear line-per-entry,
 * the title would appear as heading.

For instance:

```
date: 2018-07-22
tags: markdown, feature-request
status: published
title: Page or post title

# Heading

The first empty line is the separator.
The rest of the page is rendered normally.
```

**Comment by ancho** [comment]
This is already done. But it didn't find it's way into the documentation.
See #419 

You should be able to configure the header separator in your `jbake.properties` file with jbake 2.6.1.

```
header.separator=---------
```

You need to change all your headers, there is no fallback to the old one. Let us know if that works for you. And if you have some minutes left, please feel free to extend the documentation at https://github.com/jbake-org/jbake.org. All help is welcome ;)

**Comment by OndraZizka** [comment]
That should work :) Although, an empty line would IMO be best. Just like in MIME and HTTP.
Could it perhaps support something like `header.separator=EMPTY_LINE` in the future?

**Comment by OndraZizka** [comment]
https://github.com/jbake-org/jbake.org/pull/103

**Comment by jonbullock** [comment]
Another approach is to separate out the metadata header completely into a [sidecar file](https://github.com/jbake-org/jbake/issues/379) so the file only contains pure content.

**Comment by OndraZizka** [comment]
Right, that could work, too. A matter of taste. So maybe JBake could support both. But personally, I would go with the embedded one, plus offload elsewhere as many metadata as possible - see e.g. #496.

**Comment by OndraZizka** [comment]
https://github.com/jbake-org/jbake.org/pull/103 was merged.
