### ISSUE TITLE
Travis JDK7 test consistently fails not finding gradle-sdkvendor-plugin

### ISSUE THREAD

**Issue by OndraZizka** [jbake-org/jbake#523]
All PRs fail because Gradle is looking for a jar at https://plugins.gradle.org/m2/io/sdkman/vendors/io.sdkman.vendors.gradle.plugin/1.1.1/io.sdkman.vendors.gradle.plugin-1.1.1.jar but that's 404.

I have found https://plugins.gradle.org/m2/gradle/plugin/io/sdkman/gradle-sdkvendor-plugin/1.1.1/gradle-sdkvendor-plugin-1.1.1.jar
which is likely the same thing.

I can't fix it as I don't have much Gradle knowledge, but since there's a Growing PR backlog and this is not helping, could someone please check if that can be easily fixed? Thanks :)

 *Or* let's trash Java 7 entirely and cut a 2.7 release?

**Comment by OndraZizka** [comment]
I think this is related https://github.com/gradle/gradle/issues/5777

**Comment by ancho** [comment]
Just switch to gradle 4.9. As I mentioned in #471.
I'll do that in a few minutes.

**Comment by ancho** [comment]
But anyways. Yes. We should.

**Comment by ancho** [comment]
Btw. with gradle >= 5.0 jdk 7 is not an option anymore. They drop the support, too. JDK 11 (LTS Release)  
will be released in september.

**Comment by ancho** [comment]
@OndraZizka rebase your PR's onto master.  That should fix the travis builds now.

**Comment by OndraZizka** [comment]
Looks that it helped. Thanks!
