### ISSUE TITLE
(Feature) Externalize the markdown metadata

### ISSUE THREAD

**Issue by rferreira** [jbake-org/jbake#526]
Hello there, I think it would be tremendous if we could have the metadata for markdown files be in a separate file alongside your .md one. For example a blog1.md would have a blog1.yaml metadata file containing all the required attributes. 

Why would you like to do this? The answer is twofold: 

1. If would drive a clear separation between content and metadata keeping Markdown editors happy since they (at least intellij does) currently freaks out its syntax highlighting when parsing the metadata section 
2. It would make it easier to copy/paste content from text editors (or markdown editors) without risking to overwrite the metadata section. 

Thanks for listening.

**Comment by jonbullock** [comment]
Thanks for taking the time to open this issue, it has already been requested #379

**Comment by rferreira** [comment]
closing as dup
