### ISSUE TITLE
jbake.org is down. Perhaps let's move the site to github.io?

### ISSUE THREAD

**Issue by OndraZizka** [jbake-org/jbake#536]
JBake.org, hosted at 69.172.201.153, is currently down.
Not sure who holds the keys, but could we perhaps move it to github.io? That way, it could be 1) kept alive easily 2) updated just through PRs.

**Comment by manikmagar** [comment]
Looks like gitlab pages is down. Jbake.org is maintained in GitHub and is auto-replicated to gitlab pages for hosting public site. Any merge to jbake-org github repo would result in auto-publishing the site content.   
  

  
BTW, My other gitlab hosted sites are also giving the same error. Hopefully gitlab resolves it soon.
  

  
Regards,
  
Manik
  

  
  

  
  
>

**Comment by jonbullock** [comment]
Maybe this is the cause: https://about.gitlab.com/2018/08/28/gitlab-pages-update/ 

I'll check it out as soon as I get out of work today.

**Comment by jonbullock** [comment]
Should be working again now. Let me know if you're still seeing issues.
