### ISSUE TITLE
Upgrade Jetty to 9.2.26.v20180806

### ISSUE THREAD

**Issue by jonbullock** [jbake-org/jbake#566]
See https://groups.google.com/d/msg/jbake-user/FKN1zkYy9S8/iWbGHNWhDgAJ

**Comment by ancho** [comment]
Is the 9.4.x compatible with java7?

**Comment by ancho** [comment]
Nope. https://www.eclipse.org/jetty/previousversions.html
Since 9.3 you need java 8+.

**Comment by ancho** [comment]
So lets add this to 2.7.0 milestone. Release the small bugfixes with 2.6.4. Ditch java 7 support, and release 2.7.0 as soon as possible. what do you think?

**Comment by jonbullock** [comment]
Totally agree about dropping Java 7 in 2.7.0, this was to upgrade Jetty to the latest Java 7 supported version in the meantime. I thought the 9.2 was the last one that supported Java 7?

**Comment by ancho** [comment]
Ah. Sorry for the confusion, I misinterpreted the mail. nevermind.
