### ISSUE TITLE
Apostrophe in Post title is rendered as &amp;#8217;

### ISSUE THREAD

**Issue by obfischer** [jbake-org/jbake#582]
An apostrophe in the title of a post will be rendered as `&amp;#8217` instead of `&#8217;`. Therefore an apostrophe can't be used in the the title of blog post (Asciidoctor document). I have this problem with jBake 2.5.1 and 2.6.3.

**Comment by obfischer** [comment]
It is quite easy to reproduce:

1. Create a new Project with jBake
    plexus@nexus:/tmp> $HOME/.jbake/jbake-2.6.3-bin/bin/jbake --init
    JBake v2.6.3 (2018-10-16 13:30:01PM) [http://jbake.org]

    Base folder structure successfully created.

2. Edit the file `content/blog/2013/fourth-post.adoc` and replace the the current title by a new title containing an apostrophe
3. Build the blog and view it in a browser

**Comment by ancho** [comment]
Hi. That's a problem of an escape in the corresponding [post.ftl](https://github.com/jbake-org/jbake-example-project-freemarker/blob/eced33057cb5fc96bb9d74249e56eb71887ffd4b/templates/post.ftl#L7) template.

Remove the surrounding <#escape> tags and it should work.

**Comment by obfischer** [comment]
It works now. Thank you!
