### ISSUE TITLE
I have an issue in JBake. plz help.  i need a sample jbake project that uses custom Thymeleaf templates

### ISSUE THREAD

**Issue by iukinfopoint** [jbake-org/jbake#600]
I'm beginner at JBake.
i want to generate custom pages in output folder according to my custom templates. i've initialized my custom templates in Jbake properties but it's not creating custom output pages after baking.
i need any example html website jbake project that uses custom templates & also creates custom output html pages.
so that i can clear my concept how to implement custom templates for custom output pages by observing that example.
I'll be very thankful to you.

**Comment by jonbullock** [comment]
Have a look at: https://github.com/jbake-org/jbake-example-project-thymeleaf which is an example project using Thymeleaf. For an example on custom templates have a look at the JBake site: https://github.com/jbake-org/jbake.org

**Comment by iukinfopoint** [comment]
ok sir thank you!

**Comment by iukinfopoint** [comment]
ok sir I got it.  thank you so much..!
