### ISSUE TITLE
Documentation bad link for default.properties

### ISSUE THREAD

**Issue by zemian** [jbake-org/jbake#601]
The latest doc https://jbake.org/docs/2.6.4/ under "9. Configuration" has link for "default.properties" link to wrong page (https://github.com/jbake-org/jbake/blob/master/src/main/resources/default.properties). I think it should be https://github.com/jbake-org/jbake/blob/master/jbake-core/src/main/resources/default.properties

**Comment by ancho** [comment]
Thanks for the hint!

**Comment by jonbullock** [comment]
Fixed by @rdmueller
