### ISSUE TITLE
Suppress "unable to load engine" warning for optional template engines

### ISSUE THREAD

**Issue by bshannon** [jbake-org/jbake#602]
I'm trying to make the jbake-maven-plugin work with the latest version of JBake.
It's unfortunate that the JBake configuration API was changed incompatibly, but
I've mostly got it working.  However...

Most Maven projects don't include most template engines.  When JBake fails to
load an optional template engine, it produces a warning:

    [WARNING] unable to load engine

followed by a (huge) stack trace.  These warnings and stack traces obscure the fact
that JBake is working as expected.

JBake 2.6.0 did not produce any warning in this case.  These warnings should be removed,
or there should be a configuration option to suppress (or better yet, produce) these warnings.

The warning comes from [org.jbake.template.TemplateEngines](https://github.com/jbake-org/jbake/blob/master/jbake-core/src/main/java/org/jbake/template/TemplateEngines.java#L82).

**Comment by jonbullock** [comment]
Thanks for raising this issue @bshannon

**Comment by jonbullock** [comment]
@bshannon The jbake-maven-plugin has been updated to v0.3.2 which is compatible with JBake v2.6.4 now, although this issue still exists. I'll speak to the rest of the team and see if we can include a fix for the warnings in v2.6.5 which we're planning on releasing soon.
