### ISSUE TITLE
Groovy warnings if running/baking with JDK11 - illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by ottlinger** [jbake-org/jbake#604]
When I run the baking with JDK11 I get some errors that should be fixed (I guess either by upgrading or waiting for updates?):

`+./bin/jbake-2.6.4-bin/bin/jbake -b --reset
JBake v2.6.4 (2019-01-21 21:03:37PM) [http://jbake.org]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/home/travis/build/apache/incubator-tamaya-site/bin/jbake-2.6.4-bin/lib/groovy-2.5.5.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release`

I see similar messages in jbake-builds: e.g. https://travis-ci.org/jbake-org/jbake/jobs/531074230
`> Task :jbake-core:test
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/home/travis/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy/2.5.7/99907efe4b69f800c42584386f5d668e4d952bd5/groovy-2.5.7.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release`

**Comment by ancho** [comment]
Hi. Those are warnings coming from the groovy library. Groovy addressed some of those warnings with the latest release and the first beta of 3.0.0. With the next releases of groovy those warnings will be gone. So long, we just have to wait. They are not critical for jdk 12 and 13, too.

**Comment by ottlinger** [comment]
@ancho thanks for the info - then let's keep the issue open until all updates are in jBake :-)

**Comment by cvmocanu** [comment]
Time to use the latest Groovy release (``3.0.4``)?
If we have ``org.gradle.warning.mode=all``, this warning may train us to ignore other important warnings.

**Comment by jonbullock** [comment]
Closing issue.

JBake v2.6.6 uses Groovy v3.0.7
