### ISSUE TITLE
Inconsistencies in deployed artifacts on maven central

### ISSUE THREAD

**Issue by AFulgens** [jbake-org/jbake#607]
On maven central the published jars for versions 2.6.2, 2.6.3, and 2.6.4 do not have the class file `org.jbake.app.ConfigUtil`. Although I see that since that release 2.6.2, `ConfigUtil` is empty; still, if I try a build with JBake 2.6.2+ and JBake-Maven-Plugin 0.3.1, I get an error, namely:

```
A required class was missing while executing org.jbake:jbake-maven-plugin:0.3.1:generate: org/jbake/app/ConfigUtil
```

Downgrading to 2.6.1 solves this issue.

**Comment by ancho** [comment]
The `ConfigUtil` class moved to another package with https://github.com/jbake-org/jbake/pull/341 which broke the compatibility unfortunately . 

There is a pending pull request that should fix that problem. See https://github.com/jbake-org/jbake-maven-plugin/pull/18

The empty `ConfigUtil` shouldn't be there. I'll open a seperate issue.

**Comment by kwin** [comment]
This is only an issue in the maven plugin and was already fixed via https://github.com/jbake-org/jbake-maven-plugin/pull/17. The only thing missing is a new release of the Maven plugin...

**Comment by jonbullock** [comment]
Closing as updated Maven plugin has been released.
