### ISSUE TITLE
JSON array as complex custom metadata

### ISSUE THREAD

**Issue by nico-de** [jbake-org/jbake#611]
I'm trying to use complex custom metadata defined as a _JSON_ array in my `.adoc` file. According to the documentation 6.1.4. I've tried
```
ogs=[{"description": "Something"}, {"description": "Anything"}]
```
and in my `.ftl` file
```
<#list content.ogs as og>
   <p>${og.description}</p>
</#list>
```

However, I'm getting
```
For "#list" list source: Expected a sequence or collection, but this has evaluated to a string (wrapper: f.t.SimpleScalar): [...]
```

Are _JSON_ arrays not supported yet?

**Comment by ancho** [comment]
It does. But unfortunately the json string has to start and end with a curly bracket.

So `ogs={ "array": [{"description": "Something"}, {"description": "Anything"}] }` should work.
Hope that helps.

**Comment by nico-de** [comment]
Works like a charm. Thanks a lot. Would be great, if this was added to the documentation.
