### ISSUE TITLE
jbake command does not work on MSYS(GitBash)

### ISSUE THREAD

**Issue by yukihane** [jbake-org/jbake#612]
When executing `jbake` command on GitBash, following error occurs:

```
Error: Could not find or load main class org.jbake.launcher.Main
Caused by: java.lang.ClassNotFoundException: org.jbake.launcher.Main
```

I think it is caused by old version Gradle.
gradle/gradle#8679

**Comment by ancho** [comment]
Initial fixed by #612. Will be closed by #603 which contains gradle 6.3.
