### ISSUE TITLE
Travis job seem to be not executed

### ISSUE THREAD

**Issue by ancho** [jbake-org/jbake#628]
I noticed on pr #627 and #625 that the travis job is not listed in the checks section anymore.

**Comment by manikmagar** [comment]
For #627 , Travis seems to have ran - https://travis-ci.org/github/jbake-org/jbake/builds/668378245 but PR checks do not report that.

**Comment by ancho** [comment]
hmm...interesting. do you know how to check that?

**Comment by manikmagar** [comment]
No, exploring. Maybe some permissions changed recently.

**Comment by manikmagar** [comment]
Some had changed early 2019 - https://docs.travis-ci.com/user/migrate/legacy-services-to-github-apps-migration-guide. Do you know if we had migrated Jbake?

**Comment by ancho** [comment]
That could be it. I'm not aware of any discussion about that. So with high propability this did not happen ;)

**Comment by manikmagar** [comment]
I could see it is not activated for github app. I submitted a request to activate it and seems to be pending for admin to approve it. Do you or @jonbullock see a request in travis for jbake?

**Comment by ancho** [comment]
Seems to work now....
