### ISSUE TITLE
Adding Code formatter

### ISSUE THREAD

**Issue by manikmagar** [jbake-org/jbake#631]
Should we add a code formatter to enforce same code formatting?
See - https://github.com/sherter/google-java-format-gradle-plugin or https://github.com/sherter/google-java-format-gradle-plugin.

**Comment by ancho** [comment]
We had that discussion before. Can't find the issue right now. 
Some time ago I added a simple checkstyle configuration. See https://github.com/jbake-org/jbake/blob/master/BUILD.adoc#check-code-convention-violations

I'm using the checkstyle plugin for intellij.

**Comment by ancho** [comment]
Found the discussion in #372

**Comment by ancho** [comment]
So there is also an .editorconfig file ¯\_(ツ)_/¯

**Comment by manikmagar** [comment]
Thanks for referring to earlier discussion. I see the editorconfig and checkstyle plugin. It requires to configure IDE to use it. Will it cause the build/CI checks to fail if I don't format code according to checkstyle? I am late to that discussion now. IMO code formatting should be validated during build. If format doesn't match build should fail.

**Comment by ancho** [comment]
It's run by the ci during `./gradlew check`.
See https://docs.gradle.org/current/userguide/checkstyle_plugin.html
It can be configured to be less tolerant. But I'm not quite sure if that really is necessary.

**Comment by manikmagar** [comment]
Ok, let's stay with checkstyle then. Closing this one.
