### ISSUE TITLE
Start bakePreview with a contextPath

### ISSUE THREAD

**Issue by rdmueller** [jbake-org/jbake#641]
Is it possible to start the internal webserver with a `contextPath` or `context-root` so that the static page will be deployed to 

    http://localhost:8080/{contextPath}/

instead of

    http://localhost:8080/

?

**Comment by ancho** [comment]
I'm afraid not. But if you are using gradle you can workaround by using the gretty plugin and use a custom variable like `site.contextPath` in your configuration and templates.

https://github.com/ancho/calmdev-website/blob/master/build.gradle#L45
https://github.com/ancho/calmdev-website/blob/master/build.gradle#L25
https://github.com/ancho/calmdev-website/blob/master/src/jbake/templates/layout/main.tpl#L19

Hope that helps a bit.

**Comment by ancho** [comment]
Would be nice to configure the binding address as well. Makes it easier using the build in server in a container. Will play around with it.

**Comment by rdmueller** [comment]
yes, the gretty plugin works nice - already have it in use but wanted to make sure that a) it is needed and b) this idea floats back to jbake.

But the binding address is configurable, isn't it? https://github.com/jbake-org/jbake-gradle-plugin#previewing

**Comment by ancho** [comment]
No. Currently not. The gradle plugin uses the same class to start the jetty server. 
But an PR to configure hostname and contextpath is on it's way ;)

**Comment by rdmueller** [comment]
ah - I mixed up the port and adress, yes.
wow. the PR came quite quickly! thanx!

**Comment by rdmueller** [comment]
👍
