### ISSUE TITLE
Plans to use Rhino instead of Nashorn?

### ISSUE THREAD

**Issue by keilw** [jbake-org/jbake#656]
Currently JBake uses Nashorn, which as you may know was removed after Java 11. Are there plans to support Rhino instead, so JBake will work beyond Java 11?

**Comment by jonbullock** [comment]
I thought I'd read this wrong, replacing Nashorn with Rhino, as I wasn't aware Rhino has been continuously developed and is available separately.

I'm not aware of JBake directly using Nashorn for anything, unless a dependency is and you've run into an issue while running JBake on Java > 11?

It is a desire to support running JBake on later versions of Java though.

**Comment by keilw** [comment]
Yes because even Java 11 is outdated now. So it should run with 12 or even 17 over time. Baking with JBake there are lots of warnings that Nashorn is being used like:
```
18:26:07.140 INFO  org.jbake.app.Oven - Baking has started...
Warning: Nashorn engine is planned to be removed from a future JDK release
```
Not sure, if that's a bogus warning or Oven does use it?

**Comment by ancho** [comment]
I am also not aware that Nashorn engine is used. Interesting.

Java 11 is the current LTS Version and it's EOL is 2024/10 according to https://foojay.io/almanac/jdk-11/

**Comment by ancho** [comment]
the ci currently has some issues in general which need to be addressed but we already cover jdk 14 and should at least check always to the latest general available version which is currently jdk 15 with  jdk 16 following in march.

**Comment by keilw** [comment]
It seems it's a general warning of earlier JDKs. I currently use the Zulu distribution of Java 15 and that still works.
I know SonarQube free OSS checker forced us to upgrade to Java 11 in a few build jobs, depending on the CI tool you use that also may abandon Java 9 or 10 while 11 should still be supported at least until 2024 ;-)
