### ISSUE TITLE
handle travis-ci.org shutdown

### ISSUE THREAD

**Issue by ancho** [jbake-org/jbake#658]
There is this notification on the travis-ci but i could not find more information on this.

![Screenshot-area-2021-02-14T11:43:56+01:00](https://user-images.githubusercontent.com/264432/107874512-715fac80-6eba-11eb-9180-400d768bb437.png)

Probably just a question of migrating the account to travis-ci.com.

**Comment by ancho** [comment]
Migration needs to be initiated by the admin and you need to sign up for the beta account to migrate the repositories to travis-ci.com.

**Comment by ancho** [comment]
https://docs.travis-ci.com/user/migrate/open-source-repository-migration

**Comment by ottlinger** [comment]
@ancho due to the fact that jBake qualifies for the OSS-always-free there is no problem with the different billing taking place on travis-ci.com. After the migration do not forget to update all links in READMEs/web pages a.s.o.

**Comment by jonbullock** [comment]
I've followed the guide to migrate the project over to travis-ci.com so fingers crossed!

Thanks for the reminder @ottlinger I'll update the links now, be a good test to make sure the migration has worked :+1:
