### ISSUE TITLE
handle bintray shutdown

### ISSUE THREAD

**Issue by ancho** [jbake-org/jbake#659]
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

As of now jcenter will not accept any submissions after may 31st.

This has srveral implications for deployment and publishing the binary distribution packages.

**Comment by jonbullock** [comment]
Shame as sync to Maven Central was very useful.

How about using GitHub releases part to host the release ZIP files? Did a quick search and came across this Gradle plugin: https://github.com/BreadMoirai/github-release-gradle-plugin

**Comment by ancho** [comment]
I was thinking about that too. On the other hand we can also publish it to the webserver. I am still not quit sure if it is the best idea to bind oneself to much to github.

**Comment by ancho** [comment]
Hmm....but the plugin looks very useful indeed.

**Comment by jonbullock** [comment]
Yeah jbake.org was my first thought too. 

We could aim to publish to both.

**Comment by matthiasblaesing** [comment]
You don't need bintray to publish to maven central. Sonatype itself (they host central) offers a staging repository: OSSRH (https://central.sonatype.org/pages/ossrh-guide.html). I use OSSRH for personal projects and the JNA project.

**Comment by ancho** [comment]
Yes. Thank you. I picked this plugin as a candidate for [publishing to sonatype OSSRH](https://github.com/marcphilipp/nexus-publish-plugin#publishing-to-maven-central-via-sonatype-ossrh)

**Comment by ancho** [comment]
Everything else is already prepared https://issues.sonatype.org/browse/OSSRH-7293

**Comment by keilw** [comment]
Yes, you can check how UoM did this in https://github.com/unitsofmeasurement/uom-parent/issues/24 and individual tasks for particular subprojects and repos.
