### ISSUE TITLE
Atom feed

### ISSUE THREAD

**Issue by Golutazem** [jbake-org/jbake#665]
This feature request is to support Atom feeds.

**Comment by jonbullock** [comment]
If you check the example templates that come with JBake then you'll find a template for an Atom feed, here is a link to the Freemarker one:

https://github.com/jbake-org/jbake-example-project-freemarker/blob/master/templates/feed.ftl

**Comment by Golutazem** [comment]
Good. Would be good to advertise this more feature then.

**Comment by jonbullock** [comment]
I've updated the main jbake.org site to mention Atom as well as RSS feed.
