### ISSUE TITLE
https://jbake.org/ returns 502 status

### ISSUE THREAD

**Issue by kwin** [jbake-org/jbake#669]
The website at https://jbake.org/ return a 502 status with a generic error page rendered from Cloudfare.

**Comment by jonbullock** [comment]
Thanks for taking the time to raise this. 

GitLab Pages had an outage earlier today and that's who we use to host jbake.org behind Cloudflare.

**Comment by jonbullock** [comment]
https://gitlab.com/gitlab-com/gl-infra/production/-/issues/3962
