### ISSUE TITLE
jbake -s is not displaying the default page content 

### ISSUE THREAD

**Issue by ecabrerar** [jbake-org/jbake#685]
JBake 2.6.6 is not displaying the default page content when  jbake -s command is executed. It is displaying the directory content instead.

To reproduce the issue, I just follow the default step to create a jbake project
jbake -h
> JBake v2.6.6 (2021-03-14 23:17:22pm) [http://jbake.org]

mkdir demo-project
cd demo-project
jbake -i
jbake -b

Output
> JBake v2.6.6 (2021-03-14 23:17:22pm) [http://jbake.org]

> 16:40:47.911 INFO  org.jbake.launcher.BakeWatcher - Watching for (content, template, asset) changes in [demo-project]
> 16:40:47.986 INFO  org.jbake.launcher.JettyServer - Serving out contents of: [demo-project/output] on http://localhost:8820/

![Screenshot from 2021-05-04 16-33-18](https://user-images.githubusercontent.com/2789130/117066701-0e322900-acf7-11eb-8eee-1de1dfdb9696.png)

If you execute the same command, jbake -s, in previous versions of jbake, the content of index.html (default page) will be displayed automatically.

**Comment by jonbullock** [comment]
Thanks for raising this 👍

**Comment by jonbullock** [comment]
This line is causing the issue: https://github.com/jbake-org/jbake/blame/master/jbake-core/src/main/java/org/jbake/launcher/JettyServer.java#L52
