### ISSUE TITLE
content.nextContent is pulling in content of different type

### ISSUE THREAD

**Issue by jonbullock** [jbake-org/jbake#708]
Context:

https://pasteboard.co/K5MRObM.png

https://github.com/kiegroup/optaplanner-website/blob/master/templates/post.ftl#L61

In this scenario as you're dealing with type=post, user doesn't expect content of different types to be available. Initial feeling was this was a bug, buts needs investigating.

**Comment by ge0ffrey** [comment]
Generated website with this bug:
  https://www.optaplanner.org/blog/2021/06/09/StaticWebsiteGenerationWithJavaMavenAndJBake.html
