### ISSUE TITLE
[RFE] Add support for yaml in freemarker

### ISSUE THREAD

**Issue by bmarwell** [jbake-org/jbake#722]
Hi,

when using the `jbake-maven-plugin`, you can do this:

`<#assign releases = data.get('releases.yaml').releases>`

This is not possible when just executing `jbake -b`. :( 
My request is that this should be possible in the default jbake distribution.

## Example use case

Example pom.xml: https://github.com/kiegroup/optaplanner-website/blob/main/pom.xml

Example loading of yaml data: https://github.com/kiegroup/optaplanner-website/blob/6a608a41a6ed0a7eb2a7d9d3c4133708ba224d9c/templates/macros.ftl#L1-L4

**Comment by jonbullock** [comment]
Can I just check which version of the CLI you were trying? As support for yaml data files was only added in the RC's for 2.7.0.

**Comment by bmarwell** [comment]
Ah! Some 2.6.x version using sdkman, and then switched to a Maven template which happens to have a 2.7.x version.
😅
Sorry for the noise!
