### ISSUE TITLE
Contributing guidelines documentation and supported Java version

### ISSUE THREAD

**Issue by CraigMcDonaldCodes** [jbake-org/jbake#723]
Hello jBake,

It looks like project jumped from 7 to 8 in PR 551 but the contributing doc wasn't updated.

> At present JBake supports Java 7 and above and any contributions shouldn't use Java 8+ syntax, please see
> the roadmap for when support for Java 8 is planned.

https://github.com/jbake-org/jbake/blob/master/CONTRIBUTING.asciidoc#supported-java-versions

**Comment by jonbullock** [comment]
Thanks for catching this one @CraigMcDonaldCodes 

The contributing doc should have been updated after #551 was merged in.

**Comment by CraigMcDonaldCodes** [comment]
Corrected in #724.
