### ISSUE TITLE
Dates from data/*.yml file all have off-by-one errors on machines with american timezones

### ISSUE THREAD

**Issue by ge0ffrey** [jbake-org/jbake#726]
The automatic publisher of the optaplanner.org website has off-by-one-errors for dates. Locally I cannot reproduce this bug.

![image](https://user-images.githubusercontent.com/176880/134154329-75868097-d1bb-4a54-9d6f-161886a074fd.png)

For example, **all the event dates published on optaplanner.org live are wrong**:

![Selection_818](https://user-images.githubusercontent.com/176880/134028992-2cfa948e-9081-4dd5-b1f8-4dbcf2848234.png)

But in the events.yml file, they are correct:

```
- eventId: 20211012-icodejavaafrica
  eventOrganization: "I code Java Africa"
...
  date: 2021-10-12


- eventId: 20211025-joker
  eventOrganization: "Joker"
...
  date: 2021-10-25


- eventId: 20211119-devoxxua
  eventOrganization: "Devoxx Ukraine"
...
  date: 2021-11-19

```

I suspect this because of the timezone setting of the virtual machine and/or OS. I managed to reproduce locally by doing this:

```
git clone https://github.com/kiegroup/optaplanner-website.git
cd optaplanner-website

 mvn clean generate-resources
 // Notice how the dates are correct: Africa Tue, Joker Mon, ... 
 export TZ="America/Sao_Paulo"
 mvn clean generate-resources
 // Notice how the dates are incorrect: Africa Mon (wrong), Joker Sun (wrong), ... 
 ```

**Comment by ge0ffrey** [comment]
Interestingly, post.date dates are fine on that machine (no one-off-error).

**Comment by ge0ffrey** [comment]
I bet java.util.Date is responsible for this. It's a hame that Freemarker is not using java.time.LocalDate (Java 8+) yet.

May java.util.Date burn in hell, where it was forged.

**Comment by jonbullock** [comment]
Based on the Yaml spec it appears those date values will have a time of 00:00:00 (start of the day) and UTC timezone so when the local timezone of the machine is applied (i.e. -05:00) you get a date of the previous day. 

If you add `<#setting time_zone="GMT">` this appears to fix the date display issue by ignoring the local timezone, however I'm unsure if this causes any other issues.

**Comment by ge0ffrey** [comment]
@jonbullock Any chance JBake can just fix this for us out the box?
A) Either by defaulting the YAML parser to use the same timezone as the rest of JBake
B) or by getting YAML/Freemarker etc to use java.time.LocalDate, the modern, reliable time library, instead of The Thing That Was Created In Hell (java.util.Date)?
(I do suspect B) is more work)

**Comment by jonbullock** [comment]
Yeah still working towards that goal, last comment was a dump of my progress so far.

**Comment by jonbullock** [comment]
OK so after more investigation, Snakeyaml is using the same timezone as the rest of JBake. I was curious as to why this issue didn't seem to affect other dates (i.e. dates for content files) but after further research it does affect them in the same way. However it's probably not been noticed due to the content having a time component that meant the timezone offset didn't affect the day component.

I looked into option B and it's quite straight forward to use LocalDate in Snakeyaml, however this type is not yet supported in Freemarker so changes would be required to templates.

There is the option for JBake to explicitly override the local TimeZone (maybe via jbake.properties) in similar fashion to what it does with locale?

**Comment by ge0ffrey** [comment]
Thank you for the investigation, Jon. I've opened a discussion the Freemarker mailing list about LocalDate support.

> I looked into option B and it's quite straight forward to use LocalDate in Snakeyaml, however this type is not yet supported in Freemarker so changes would be required to templates.

I am happy to make such changes. It would be great to have a jbake.properties option to turn this behavior on (preferJavaTime=true ?) even if it's just for yaml. _Anything to ban the use of java.util.Date._

> There is the option for JBake to explicitly override the local TimeZone (maybe via jbake.properties) in similar fashion to what it does with locale?

Not sure what you mean here. I think that if jbake.properties fixes a timezone, then all techs (snakeyaml, freemarker, etc) should be explicitly set to use that. If it doesn't fix a timezone, they should all be using the default timezone of the process (= of the OS). In both cases, java.util.Date's won't suddenly change timezone, because there will only be one timezone.
