### ISSUE TITLE
Hide CompositeConfiguration

### ISSUE THREAD

**Issue by RainerW** [jbake-org/jbake#73]
The configuration is primarily based on CompositeConfiguration. There are many magic invokes like : `config.getString("content.folder")`

Should be replaced by a JBakeConfiguration class. 

```
class JBakeConfiguration {
    public String getContentFolder() { ... }
    ...
```

This would make it 
- typesafe 
- create a list/class of _all_ possible config values
- IDE support to find all usage of config X

}

**Comment by jonbullock** [comment]
Addressed by #341
