### ISSUE TITLE
data.get('file.yaml') will return `class com.orientechnologies.orient.core.db.record.OTrackedMap`

### ISSUE THREAD

**Issue by bmarwell** [jbake-org/jbake#747]
for example, given this file:
https://github.com/apache/shiro-site/blob/6b06cb888e04febf8216d82c1043fb27eea45044/data/authors.yaml

## actual behaviour

When importing using
`<#assign authors = data.get('authors.yaml').authors />`

The returned type will be `com.orientechnologies.orient.core.db.record.OTrackedMap`

## expected behaviour

A hash is returned without methods like `getClass()`. Just the author names as keys and the data as values.

## version

```xml
          <dependency>
            <groupId>org.jbake</groupId>
            <artifactId>jbake-core</artifactId>
            <version>2.7.0-rc.4</version>
          </dependency>
```

**Comment by jonbullock** [comment]
Thanks for sample file, I'll have to investigate this further.

**Comment by jonbullock** [comment]
Snakeyaml returns a LinkedHashMap which is put into OrientDB but it returns the OTrackedMap instead, need to understand why this is happening first before changing anything.
