### ISSUE TITLE
Release 2.7.0-rc6 not available on Maven Central

### ISSUE THREAD

**Issue by kwin** [jbake-org/jbake#767]
The newest release 2.7.0-rc6 has been tagged yesterday but unfortunately still is not available from Maven Central: https://repo1.maven.org/maven2/org/jbake/jbake-core/

**Comment by jonbullock** [comment]
@kwin I ran into an issue (artifacts weren't signed) but I've resolved that and 2.7.0-rc6 should be available from Maven Central shortly.

**Comment by jonbullock** [comment]
Checked and 2.7.0-rc.6 is now available from Maven Central.
