### ISSUE TITLE
Asciidoctor include directive does not strip document header attributes in included file

### ISSUE THREAD

**Issue by lefou** [jbake-org/jbake#79]
Here a minimal example:

My documentation is splitted into multiple pages, e.g. the `Installation.adoc` file start like this:

```
= Installation
My Name
2014-01-18
:revversion: svn
:jbake-type: page
:jbake-status: published

== Heading

Text text text.
```

Additionally, I want to habe a single-page Documentation which includes all other parts. `Documentation.adoc`:

```
= Documentation
My Name
2014-01-18
:jbake-type: page
:jbake-status: published

:leveloffset: 1

include::Installation.adoc[]

:leveloffset: 0
```

Unfortunately, the special lines containing the authors, the date and other attributes are included in the resulting page as normal text. As far as I experienced, those lines should be stripped of the output.

EDIT: I'm using JBake 2.2.1-SNAPSHOT built from ef6cd8eb8f8df923dc6ca96a7acc76e6680136dc.

**Comment by cyChop** [comment]
Your comment helped me with the situation, but I add a reference for future people who might use it:

The available variables are documented in Asciidoctor's user manual: https://asciidoctor.org/docs/user-manual/#doc-header
