### ISSUE TITLE
AsciiDoc table of contents is not rendered

### ISSUE THREAD

**Issue by lefou** [jbake-org/jbake#80]
A AsciiDoc table of contents is not generated, when `:toc:` is used.

See http://asciidoctor.org/docs/user-manual/#user-toc.

JBake version is 2.2.1-SNAPSHOT, 7be8a72022e6b7f908ba2e5386ec5affccd10c98

**Comment by nyeates** [comment]
I dont pretend to understand what all this is, or what jbake is for that matter, but the TOC stuff is still 'broken' in github public. Thx for workaround!

**Comment by laplasz** [comment]
if I am using only :toc: macro, then I get a ToC at the left side of the doc - so toc::[] not needed, but without 'macro' value it is not rendered

**Comment by hohwille** [comment]
It used to work like this:
```
:toc:
toc::[]
```

However, it stopped working recently with a silent update of github platform :-1: 
Is someone still able to get a TOC for Asciidoc on Github wiki?

**Comment by jonbullock** [comment]
GitHub upgraded to Asciidoctor v1.5.2 recently: https://twitter.com/mojavelinux/status/628344681672241152

See above for solution: https://github.com/jbake-org/jbake/issues/80#issuecomment-60754340

**Comment by Hanserfaust** [comment]
As of 2016-02-23, i looked at the examples here to make my TOC work:
https://raw.githubusercontent.com/opendevise/asciidoc-samples/master/demo.adoc

My exact lines to make TOC work was this:

<CUT AND PASTE BELOW THIS LINE>
Foobar API documentation.
v1.2, 2016-02-15
:library: Asciidoctor
:idprefix:
:numbered:
:imagesdir: images
:toc: manual
:css-signature: demo
:toc-placement: preamble
//:max-width: 800px
//:doctype: book
//:sectids!:

Any questions regarding the API can be sent to /dev/null.
<CUT AND PASTE ABOVE THIS LINE>

Note that the TOC dit NOT appear if i left out the last line "Any questions...".
